Feature/#96 게시글 생성 기능 구현
KEEPER31337/Homepage-Back-R2 pull request #112
Opened 2023-02-11 13:28 UTC by shkisme

## 🔥 Related Issue

close: #96

## 📝 Description

게시글 생성(작성) 기능을 구현하였습니다.
Posting에서 Comment 도메인을 분리하였습니다. (서비스도 기능별로 분리하는게 좋아보여서 그렇게 할 예정입니다.)

## ⭐️ Review

테스트 코드를 열심히 참고하면서 작성을 해 봤는데, 맞게 잘 작성을 한건지, 추가해야 할 테스트가 더 있는지에 대해서 고민이 많이 됩니다.
+) 방학이 아쉽게도 얼마 남지 않았네요. 더 열심히 해야겠습니다!

> @gusah009 선배님이 만들어주신 썸네일&파일 유틸리티 덕에 편하게 개발할 수 있었습니다. 🙇‍♀️

2023-02-12 22:06 UTC, hyuunnn requested changes

2023-02-13 01:08 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/posting/api/PostingController.java
> +  }
Restful Api 에 대해서 한번 더 생각해보게 되었네요 감사합니다! 👍 create 라는 행위는 빼는 게 좋겠네요!

2023-02-13 01:10 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/posting/api/PostingController.java
> +  }
또, posting 도 게시글을 작성하는 행위를 나타내는 것이라, 이 부분도 고민해보고 수정하는 게 좋겠네요!

2023-02-13 01:11 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/posting/api/PostingControllerTest.java
> +    }
으악 바로 수정하겠습니다!

2023-02-13 02:42 UTC, shkisme commented
`Posting` 이 **게시글을 올린다는 행위**를 포함하고 있는 단어이기 때문에, 모든 `Posting`을 `Post`로 수정하게 되었습니다...! 네이밍을 할 때 오던 위화감이 여기에 있었네요... 미리 발견 할 껄 ㅠㅠ
때문에 변경사항이 많아져서 api 기능에 대한 변경점을 알아보기 힘들게 된 점 미리 죄송합니다... 😅

2023-02-13 02:57 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/posting/api/PostingControllerTest.java
> +    }
mockMvc.perform(multipart(HttpMethod.PATCH, "/users") 다음에 file을 담아서 보내야 하기 때문에, 조금 더 직관적이도록 코드들을 수정해보았는데 봐주시면 감사합니다!

2023-02-13 04:22 UTC, gusah009 requested changes
수고 많으셨습니다!@!! 리뷰가 늦었네요~!

`Posting` → `Post`로 바꾼 이유가 있을까요? 저희가 처음 테이블 작성할 때 `user`나 `post`를 쓰지 않은 이유가 예약어로 존재해서였는데,(HTTP의 POST와 포스팅의 POST) 바꾸신 이유가 있으신지 궁금합니다.

2023-02-13 04:22 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/post/application/PostService.java
> +    }
탈출 조건문을 함수 초기에 줘서 가독성이 좋아진 것 같습니다! 👍👍

2023-02-13 04:22 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/post/application/PostService.java
> +  }
❗️ 카테고리에서 포스팅의 생명주기를 관리하도록 `cascade = ALL`을 설정하신걸로 알고 있는데, 이건 `postRepository`가 생명주기를 관리하고 있는 것 같습니다. 아예 `category`의 `cascade`를 제거하거나 아래와 같이 작성해보시는건 어떠신가요?

```java
Category category = getCategoryById(request.getCategoryId());
category. addPost(post);
return categoryRepository.save(category).getPostList().get(0);
```

2023-02-13 04:22 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/posting/application/PostingServiceTest.java
> +    void should_success_when_createPost() {
테스트가 잘 작성돼있는 것 같아요 😄

2023-02-13 04:22 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/posting/api/PostingControllerTest.java
> +          .andDo(document("create-post",
`location`도 확인해보면 좋을 것 같습니다!

2023-02-13 04:22 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/posting/api/PostingControllerTest.java
> +          .contentType(MediaType.MULTIPART_FORM_DATA));
`callApi()` 좋네요 ㅎㅎ

2023-02-13 04:22 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/post/application/PostService.java
> +  }
+) 개인적인 의견이긴한데 `request`를 `service`에서 받지 않고, 컨트롤러에서 `entity`를 만들어서 넘겨줘도 좋을 것 같습니다!

계층별로 구분하기도 쉬워지고, 무엇보다 `PostService#createPost` 메서드를 다른 곳에서 재사용이 수월해질 것 같습니다!

별로라고 생각되시면 굳이 안그러셔도 됩니다! ㅎㅎ 😄

2023-02-13 04:54 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/posting/dto/request/PostRequest.java
> +  private String password;
아 그럴 수 있겠네요!! 확인하고 반영하겠습니다!

2023-02-13 04:55 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/post/application/PostService.java
> +  }
그러네요! `category`의 `cascade`를 제거하는 것이 직관적인 것 같습니다 감사합니다!

2023-02-13 23:03 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/post/application/PostService.java
> +  }
고민해보면서 `service` 가 `request` 없이 돌아가도록 만들어 보았는데 이렇게 하니 컨트롤러가 많은 역할을 하게 되는 것 같습니다...! 이런 느낌을 말하신 건지 궁금합니다!

```java
public ResponseEntity<Void> createPost(
      @LoginMember Member member,
      @ModelAttribute @Valid PostRequest request
  ) {
    Thumbnail savedThumbnail = thumbnailUtil.saveThumbnail(request.getThumbnail()).orElse(null);
    Post post = request.toEntity(member, WebUtil.getUserIP(), savedThumbnail);
    Category category = postService.getCategoryById(request.getCategoryId());
    Long postId = postService.createPost(post, category);
    postService.savePostFiles(request.getFiles(), post);

    return ResponseEntity.status(HttpStatus.CREATED)
        .location(URI.create("/posts/" + postId))
        .build();
  }
```

2023-02-14 05:37 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/post/application/PostService.java
> +  }
@shkisme 음... 저는 `request`에 의존하지 말자는 생각으로 의견을 냈던 거라 아래같은 코드를 생각하긴 했습니다!

```java
public ResponseEntity<Void> createPost(
      @LoginMember Member member,
      @ModelAttribute @Valid PostRequest request
  ) {
    long postId = postService.save(request.toEntity(member, WebUtil.getUserIP()),
                                    request.getCategoryId(),
                                    request.getThumbnail(),
                                    request.getFiles());

    return ResponseEntity.status(HttpStatus.CREATED)
        .location(URI.create("/posts/" + postId))
        .build();
  }
}
```

2023-02-14 05:45 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/post/application/PostService.java
> +  }
엇..! 그러네요 ㅋㅋㅋㅋㅋㅋㅋ 왜 저렇게 생각했었을까요? ;; 이렇게 수정 해보도록 하겠습니다!

2023-02-14 05:56 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/post/entity/category/Category.java
>    private final List<Post> posts = new ArrayList<>();
`orphanRemoval`은 살려두셨네요? 게시글 삭제는 카테고리가 관리하나요?

+) `cascade = REMOVE`도 지우신건 카테고리가 지워져도 게시글은 지우지 않겠다는 뜻인가요?

2023-02-14 05:56 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/post/application/PostService.java
> +    return postRepository.save(post);
이제 `post`의 생명주기를 관리하는 주체가 `category`가 아니라 `post`로 바뀌었는데 여전히 `category.addPost(post)`를 하고 있는 것 같습니다!

포스팅을 만들 때 `category`를 지정해주고 있어서 `category.addPost()` 메서드는 없어도 될 것 같은데 어떻게 생각하시나요?

2023-02-14 05:57 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/post/application/PostService.java
> +    return postRepository.save(post);
뒷 쪽에서 수정됐네요..! `post.addCategory(category)`로 바꾸는건 어떻게 생각하시나요?

2023-02-14 06:02 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/post/entity/category/Category.java
>    private final List<Post> posts = new ArrayList<>();
사실 카테고리가 삭제되면 게시글이 삭제되도록 개발하는 게 맞는 설계인지 계속 고민이 됩니다...! 직관적으로는 그게 맞는 거 같은데, 기획 상 저희 홈페이지에 **카테고리 관리 기능**이 없더라구요...! 카테고리가 추가, 삭제 될 일이 없는데도 역시 그렇게 만드는 게 맞겠죠?

2023-02-14 08:14 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/post/entity/category/Category.java
>    private final List<Post> posts = new ArrayList<>();
방금 팀원분들과 회의한 결과, 카테고리가 삭제되었을 때 게시글이 삭제되는 게 위험한 것 같다? 혹은 보통은 그러지 않고 미확인 카테고리로 등록되는 것 같다?는 의견이 있었는데 저도 맞는 말인 것 같아서 이 방향으로 바꿔볼까 하는데 혹시 어떻게 생각하시나요?!

2023-02-14 09:34 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/post/entity/category/Category.java
>    private final List<Post> posts = new ArrayList<>();
너무 좋아요!

2023-02-14 09:35 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/post/entity/category/Category.java
>    private final List<Post> posts = new ArrayList<>();
너무 좋아요!

2023-02-15 17:52 UTC, shkisme commented
## 추가 수정사항

`catetgory`, `comment`의 `parent_id` 컬럼을 `self referencing`으로 변경된 DB 에 맞게 수정하였습니다.

### Category Entity
```java
@OneToMany(mappedBy = "parent", cascade = ALL, orphanRemoval = true)
private final List<Category> children = new ArrayList<>();
```
부모 카테고리가 자식 카테고리의 생명주기를 관리하도록 설정했습니다. 
사실 현재의 카테고리는 거의 정적이라, 크게 신경쓰지는 않아도 될 것 같긴 합니다!
### Comment Entity
```java
@OneToMany(mappedBy = "parent", cascade = PERSIST)
private final List<Comment> children = new ArrayList<>();
```
댓글의 경우에는, 부모 댓글이 삭제되었을 때 자식 댓글이 삭제되면 안되기 때문에 `cascade = PERSIST`로 설정했습니다. 부모 댓글 삭제 시 테스트를 하려다가, 한번에 부모 댓글의 pk 를 null로 바꿔주는 JPA 기능은 없나...? 하고 찾아보다가 [찾은 글](https://www.inflearn.com/questions/39769/%EB%B6%80%EB%AA%A8-%EC%9E%90%EC%8B%9D%EA%B4%80%EA%B3%84%EC%97%90%EC%84%9C-%EB%B6%80%EB%AA%A8-%EC%82%AD%EC%A0%9C%EC%8B%9C-set-null%EB%B0%A9%EB%B2%95%EC%97%90-%EB%8C%80%ED%95%B4%EA%B6%81%EA%B8%88%ED%95%A9%EB%8B%88%EB%8B%A4)입니다.

> JPA는 객제지향 스타일로 개발 하는 것이 원칙입니다. 따라서 부모 엔티티를 삭제하기 전에 자식 엔티티를 찾고, 부모 엔티티와 연관관계를 null 처리 하는 것이 맞습니다.

2023-02-15 17:58 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/post/entity/category/Category.java
>    private final List<Post> posts = new ArrayList<>();
> `orphanRemoval`은 살려두셨네요? 게시글 삭제는 카테고리가 관리하나요?
> 
> +) `cascade = REMOVE`도 지우신건 카테고리가 지워져도 게시글은 지우지 않겠다는 뜻인가요?

늘 이렇게 성장할 수 있는 리뷰를 해주셔서 감사합니다 ㅎㅎ...! 따봉👍

2023-02-17 04:31 UTC, xet-a approved these changes
수고 많으셨습니다!! 🤗👏👏
`Post`에서 `Comment` 도메인 분리한 거 좋은 것 같아요! 구현할 부분은 더 많아지겠지만..
양방향 연관관계는 봐도봐도 어렵지만.. 그래도 덕분에 `cascade`와 `orphanRemoval` 속성에 대해 더 깊이 공부해보네요!! 😀 파이팅!

2023-02-17 04:31 UTC, xet-a commented on src/test/java/com/keeper/homepage/domain/post/dao/PostRepositoryTest.java
> +      post = postRepository.findById(post.getId()).orElseThrow();
양방향 연관관계에서 flush, clear 수행 후 다시 find로 조회하는 부분 배워갑니다 ! 👏👏👍

2023-02-17 04:31 UTC, xet-a commented on src/main/java/com/keeper/homepage/domain/member/entity/comment/MemberHasCommentDislike.java
> +  @JoinColumn(name = "member_id", nullable = false, updatable = false)
update 되지 않는 필드들에 대해 false 속성 걸어주신점 좋네요!

2023-02-17 04:31 UTC, xet-a commented on src/test/java/com/keeper/homepage/domain/post/dao/PostRepositoryTest.java
> +      em.flush();
`delete` 전, 후로 flush, clear를 수행하시는 이유가 있나요?? ((정말.. 궁금해서..))
위쪽 테스트들에서는 `delete` 전 flush, clear를 삭제하셨길래 궁금해서요!

2023-02-17 04:42 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/post/dao/PostRepositoryTest.java
> +      em.flush();
`delete` 전에 영속성을 날릴 필요가 있을까? 싶어서 기존에 있던 걸 삭제했고, `delete` 후 영속성을 `flush`, `clear`로 한번 날리고 레포지토리에서 깔끔하게 조회하고 싶어서 이렇게 했습니다!

2023-02-17 04:46 UTC, shkisme commented
> 수고 많으셨습니다!! 🤗👏👏 `Post`에서 `Comment` 도메인 분리한 거 좋은 것 같아요! 구현할 부분은 더 많아지겠지만..

`Post`와 `Comment`를 같이 두자니, `Post` 도메인의 기능이 너무 커져버리는 것 같아.. 나눠보았습니다!! 댓글 관련 기능들은 분리하여  `Comment`에 둘 생각입니다!

2023-02-17 11:26 UTC, gusah009 reviewed
길고 길었던 **게시글 생성 기능 구현 PR**이 드디어 마무리 되었네요! ㅎㅎ 고생 많으셨습니다!

👍👍👍👍👍👍

2023-02-17 11:27 UTC, gusah009 approved these changes

2023-02-17 11:54 UTC, hyuunnn approved these changes
고생하셨습니다~~!!

2023-02-17 11:54 UTC, hyuunnn commented on src/main/java/com/keeper/homepage/domain/post/api/PostController.java
> +        request.getFiles());
별거 아닌데 이렇게 하면 조금 더 깔끔할 것 같아요 ㅋㅋ
```java
    Long postId = postService.createPost(
        request.toEntity(member, WebUtil.getUserIP()),
        request.getCategoryId(), request.getThumbnail(),
        request.getFiles());
```

2023-02-17 11:54 UTC, hyuunnn commented on src/main/java/com/keeper/homepage/domain/post/application/PostService.java
> +    files.forEach(post::addFile);
`forEach` 좋습니다 ㅎㅎ

2023-02-17 11:54 UTC, hyuunnn commented on src/main/java/com/keeper/homepage/domain/post/dto/request/PostRequest.java
> +      + "자 이하로 입력해주세요.")
찾아보니까 아래 코드처럼 만들 수 있다는데 된다면 코드가 더 간결해지겠네요! <a href="https://stackoverflow.com/questions/7084706/hibernate-validator-length-how-to-specify-separate-message-for-min-and-max">stackoverflow 답변</a>
```java
@Length(max = MAX_REQUEST_PASSWORD_LENGTH, message = "비밀번호는 {max}자 이하로 입력해주세요.")
```

2023-02-17 11:54 UTC, hyuunnn commented on src/main/java/com/keeper/homepage/domain/post/entity/Post.java
> +  public static final int MAX_PASSWORD_LENGTH = 512;
혹시 `public`을 사용한 이유가 있을까요?

2023-02-17 11:58 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/post/dto/request/PostRequest.java
> +      + "자 이하로 입력해주세요.")
와 대박~~~~ 감사합니답!

2023-02-17 11:59 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/post/entity/Post.java
> +  public static final int MAX_PASSWORD_LENGTH = 512;
앗! DTO에서 요청 받는 값의 제약으로 넣으려고 public으로 열었다가 기획상의 최댓값으로 변경했으니 private으로 닫아야겠네요!! 감사합니다!!

2023-02-17 12:39 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/post/api/PostController.java
> +        request.getFiles());
감사합니다!

2023-02-17 13:07 UTC, merged