Feature/세미나 추가 삭제 구현
KEEPER31337/Homepage-Back-R2 pull request #114
Opened 2023-02-12 20:43 UTC by hyuunnn

## 🔥 Related Issue

close: #80

## 📝 Description

세미나 추가, 삭제 기능 구현을 완료했습니다!

테스트 코드도 작성했습니다!

## ⭐️ Review

군더더기 없는 테스트 코드를 작성한 것 같아서 기분이 좋습니다 :)

2023-02-13 03:46 UTC, shkisme reviewed
코드가 깔끔한 것 같아요!! 👍

2023-02-13 03:46 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/seminar/entity/Seminar.java
> +package com.keeper.homepage.domain.seminar.entity;
도메인 분리 좋습니다 👍

2023-02-13 03:46 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/seminar/api/SeminarController.java
> +public class SeminarController {
추후 회원용 api 도 생기니까 관리자용 Controller를 따로 두거나, 메서드 단위? 에 `@Secured`를 두는 건 어떨까요?

2023-02-13 03:46 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/seminar/application/SeminarService.java
> +  }
스트림 사용 👍...

2023-02-13 03:46 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/seminar/dto/request/SeminarSaveRequest.java
> +  private LocalDateTime latenessCloseTime;
`@JsonFormat(pattern = "yyyy-MM-dd HH:mm")` 어노테이션을 사용하고, 요청 시간 양식을 프론트와 협의해서 맞추면 좋을 것 같아요!
또, 요청 값이 `null` 일 수 있다면 `@Nullable` 어노테이션을 사용하는 것도 좋을 것 같아요!

2023-02-13 03:46 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/seminar/api/SeminarControllerTest.java
> +      makeSeminarUsingApi(adminToken).andExpect(status().isOk());
세미나 생성 성공 테스트 까지 같이 진행되는 느낌이 들어요. 문제가 없을까요? (저도 잘 몰라서 여쭤봅니다...ㅎ)

2023-02-13 03:46 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/seminar/api/SeminarControllerTest.java
> +          // virtual_seminar 컬럼을 포함하여 생성된 세미나는 2개가 존재한다.
`virtual_seminar`도 세미나 데이터니까, 세미나 데이터를 생성하지 않아도 이 데이터가 잘 조회되는 지 확인할 수 있지 않을까요?

2023-02-13 03:52 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/seminar/application/SeminarService.java
> +  }
하루에 **세미나는 하나만 생성 가능하다** 라는 제약에 대한 처리는 진행하지 않나요? 기획이 그렇게 된다면 백엔드에서 처리하는게 좋아 보입니다 😎

2023-02-13 03:57 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/seminar/api/SeminarControllerTest.java
> +          // virtual_seminar 컬럼을 포함하여 생성된 세미나는 2개가 존재한다.
생각해보니 클라이언트에서 `virtual_seminar`는 조회되지 않도록 처리를 해야겠네요! 죄송합니다 😅

2023-02-13 03:57 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/seminar/api/SeminarControllerTest.java
> +    }
컨트롤러 테스트만 진행하고 api 문서는 아직 뽑지 않으신건가요?

2023-02-13 07:08 UTC, gusah009 requested changes
공을 많이 들였다는 느낌이 많이 드는 코드였습니다!

수고 많으셨어요~! 👍👏👍👏

2023-02-13 09:36 UTC, hyuunnn commented on src/main/java/com/keeper/homepage/domain/seminar/api/SeminarController.java
> +public class SeminarController {
일단 따로 분리할지 하나에 넣을지 고민해보겠습니다!

2023-02-13 09:37 UTC, hyuunnn commented on src/main/java/com/keeper/homepage/domain/seminar/dto/request/SeminarSaveRequest.java
> +  private LocalDateTime latenessCloseTime;
감사합니다 반영하겠습니다 ㅎㅎ

2023-02-13 09:46 UTC, hyuunnn commented on src/test/java/com/keeper/homepage/domain/seminar/api/SeminarControllerTest.java
> +      makeSeminarUsingApi(adminToken).andExpect(status().isOk());
일단 삭제를 시도하기 전에 세미나를 만들어야 해서 저렇게 했어요 ㅋㅋ..

2023-02-13 09:51 UTC, hyuunnn commented on src/main/java/com/keeper/homepage/domain/seminar/application/SeminarService.java
> +  }
그러네요 제가 의견 제시하고 기능 구현을 안했네요 ㅋㅋ

2023-02-13 09:52 UTC, hyuunnn commented on src/test/java/com/keeper/homepage/domain/seminar/api/SeminarControllerTest.java
> +    }
아 추가하겠습니다!

2023-02-13 09:58 UTC, hyuunnn commented on src/main/java/com/keeper/homepage/domain/seminar/api/SeminarController.java
> +  }
deleteSeminar, getSeminar 등등 `long`으로 바꾸면 될까요?
지금까지 봤던 책이나 강의들도 `Long`을 사용해서 크게 문제는 없는 것 같아요.
혹시 어떻게 생각하시나요?

2023-02-13 10:03 UTC, hyuunnn commented on src/main/java/com/keeper/homepage/domain/seminar/application/SeminarService.java
> +  private final SeminarRepository seminarRepository;
수정했습니다!

2023-02-13 10:03 UTC, hyuunnn commented on src/main/java/com/keeper/homepage/domain/seminar/dto/response/SeminarResponse.java
> +@RequiredArgsConstructor
그러네요 삭제하겠습니다 ㅎㅎ...

2023-02-13 10:05 UTC, hyuunnn commented on src/test/java/com/keeper/homepage/domain/seminar/api/SeminarControllerTest.java
> +          // virtual_seminar 컬럼을 포함하여 생성된 세미나는 2개가 존재한다.
생각해보니까 API를 통해서 virtual_seminar 데이터를 조회하는게 맞지 않네요 ㅋㅋ.. 필터링 기능 추가하겠습니다.

2023-02-13 10:11 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/seminar/api/SeminarController.java
> +  }
API 스펙상 NULL이 들어와도 올바른 응답을 내려준다면 상관없을 것 같은데, 이 부분은 그런 내용이 아닌 것 같아서 말씀드렸습니다!

2023-02-13 19:48 UTC, hyuunnn commented on src/main/java/com/keeper/homepage/domain/seminar/api/SeminarController.java
> +public class SeminarController {
일단 API들 추가로 만들어보면서 구조 어떻게 할지 고민해볼게요!
일단 admin 관련 컨트롤러들이라서 그대로 두겠습니다.

2023-02-13 19:50 UTC, hyuunnn commented on src/test/java/com/keeper/homepage/domain/seminar/api/SeminarControllerTest.java
> +          // virtual_seminar 컬럼을 포함하여 생성된 세미나는 2개가 존재한다.
https://github.com/KEEPER31337/Homepage-Back-R2/pull/114/commits/90ca32a911cb9ff7d8046fd668c48da46aa96b9a -> SeminarRepository.java
https://github.com/KEEPER31337/Homepage-Back-R2/pull/114/commits/02edb6c891aa9e28f4a869a314ea649ae69a6ca7 -> SeminarRepositoryTest.java
virtual_seminar를 조회할 수 없게 수정했습니다.

2023-02-13 19:53 UTC, hyuunnn commented on src/main/java/com/keeper/homepage/domain/seminar/application/SeminarService.java
> +  }
이 기능은 세미나 날짜 조회 기능 구현 파트에서 추가하겠습니다!
쿼리 메서드로 만든 `findByOpenTime`를 `SeminarRepository`에 구현했는데 해당 메서드를 사용하면 될 것 같아요.

2023-02-13 20:11 UTC, hyuunnn commented
##나

2023-02-13 20:29 UTC, hyuunnn commented
### 주요 변경 사항

1. `SemianrRepository`에서 사용할 수 있는 `findAll`을 default 메서드로 재정의했습니다. https://github.com/KEEPER31337/Homepage-Back-R2/pull/114/commits/90ca32a911cb9ff7d8046fd668c48da46aa96b9a
수정 코드 및 커밋 로그에 적은 내용 읽어보시고 의견 들어보고 싶습니다!
2. 테스트 코드가 유동적으로 동작할 수 있게 수정했습니다. https://github.com/KEEPER31337/Homepage-Back-R2/pull/114/commits/02edb6c891aa9e28f4a869a314ea649ae69a6ca7
수정 전 코드는 특정 숫자를 사용하기 때문에 `@Rollback(false)` 설정으로 DB에 데이터가 저장된 후 테스트 코드를 다시 돌렸을 때 실패합니다. (테스트 코드는 별도의 조치 없이 언제 실행해도 항상 정상 동작을 해야 합니다.)
추가로 변경 사항 1번으로 테스트 코드에서 `filter`를 제거하였습니다.

### 보류

1. select 쿼리 줄이기
```java
public List<SeminarResponse> findAll() {
    return seminarRepository.findAll().stream()
        .map(SeminarResponse::new)
        .toList();
  }
```
위 코드는 `findAll`로 모두 가져온 후 매핑하여 이중으로 동작하기 때문에 회의에서 repository를 dto로 반환하여 불필요한 과정을 줄이면 어떨까? 의견을 냈었습니다.
API를 계속 구현하면서 추가해도 괜찮을지 고민해보겠습니다. (트래픽이 많지 않아서 그대로 둬도 상관 없을 것 같아요.)

2. 하루에 세미나 하나만 생성 가능하게 코드 수정하기
<a href="https://github.com/KEEPER31337/Homepage-Back-R2/blob/feature%2F%EC%84%B8%EB%AF%B8%EB%82%98-%EB%82%A0%EC%A7%9C-%EC%A1%B0%ED%9A%8C-%EA%B8%B0%EB%8A%A5-%EA%B5%AC%ED%98%84/src/main/java/com/keeper/homepage/domain/seminar/dao/SeminarRepository.java#L12">findByOpenTime - SeminarRepository.java</a>을 사용하여 만들 예정입니다.
merge되면 세미나 날짜 조회 기능 구현 파트에서 추가 하겠습니다.

2023-02-14 05:27 UTC, gusah009 approved these changes
너무 수고 많으셨습니다! 많은 고민을 하신 게 느껴지네요!!

> 1. SemianrRepository에서 사용할 수 있는 findAll을 default 메서드로 재정의했습니다.

코드가 너무 깔끔해져서 많이 놀랐습니다... 최고..!

> 테스트 코드가 유동적으로 동작할 수 있게 수정했습니다. https://github.com/KEEPER31337/Homepage-Back-R2/commit/02edb6c891aa9e28f4a869a314ea649ae69a6ca7
수정 전 코드는 고정된 숫자를 사용하기 때문에 @Rollback(false) 설정으로 DB에 데이터가 저장된 후 테스트 코드를 다시 돌렸을 때 실패합니다. (테스트 코드는 별도의 조치 없이 언제 실행해도 항상 정상적으로 동작해야 합니다.)

너무 좋습니다! 말씀하신 대로 테스트 코드는 어떤 상황에서도 성공해야 하는 게 맞습니다.

다만, 테스트 로직이 진행되는 상황은 대부분 DB가 default 상태일 때 입니다. 그래서 이 부분은 신경 쓰면 좋지만, 개발하는데 시간에 쫓기고 있는 상황이라면 굳이 신경쓰시지 않으셔도 될 것 같습니다! 😄

> API를 계속 구현하면서 추가하는게 좋을지 고민해보겠습니다. (트래픽이 많지 않아서 그대로 둬도 상관 없을 것 같아요.)

동의합니다!

## 질문

> SeminarControllerTest의 존재하지 않는 세미나를 삭제했을 때 실패한다 코드에서 어차피 존재하지 않는 id 값으로 삭제를 시도하기 때문에 별도의 세미나 생성이 불필요하다고 생각이 드네요.. 지울까요??

넵 지워도 좋을 것 같습니다 ㅎㅎ

> @woo-chang 님이 @Valid 어노테이션을 알려주셔서 처음에는 @Future 어노테이션으로 미래 시간인지 체크했었는데, 지금은 검증하는 메서드를 사용하기 때문에 불필요하다고 생각이 드네요..! 의견이 궁금합니다!

저도 이 부분이 정말 딜레마인데요, `request`에서 보통 사용자의 값을 검증하고 서비스에서도 다시 한 번 검증하는게 올바른 설계이긴 한 것 같습니다. 컨트롤러에서만 사용자 입력을 검증하도록 했을 때 다른 서비스에서 사용하면 입력값 검증을 생략하게 되기 때문에 둘 다 검증해주는 게 올바른 설계이긴 한 것 같습니다..!

그래서 저는 `Member` 클래스에서처럼 `@Embedded`를 적극 활용했습니다. 각 클래스가 각자의 데이터에 대해 검증 과정을 가지고 있기 때문에 중복 코드가 발생하지 않으면서 도메인에 맞는 검증을 할 수 있게 되었습니다.

물론 성능 상으론 한 번만 검증할 껄 두 번 검증하는 것이기 때문에 비효율적인게 맞지만, 크게 신경쓰지 않아도 될 정도라고 생각합니다.

- **그 어떤 핑계보다 효율성이라는 이름 아래 행해진 컴퓨팅 죄악이 더 많다.** - 윌리엄 울프
- **자그마한 효율성은 모두 잊자. 섣부른 최적화가 만악의 근원이다.** - 도널드 크누스
- **최적화를 할 때는 다음 두 규칙을 따르라. 첫 번째. 하지 마라. 두 번째, (전문가 한정) 아직 하지마라. 다시 말해, 완전히 명백하고 최적화 되지 않은 해법을 찾을 때까지는 하지 마라.** - M. A. 잭슨


==== 아래는 제 개인 의견이니 무시하셔도 상관 없습니다! ====
대부분의 테스트를 `Controller` 테스트로 만들어주셨는데, 이전에 카톡에서 컨트롤러에서 통합테스트를 진행하면 되지 않냐는 말씀대로 작성해주신 것 같아요!

물론 이 때문에 테스트가 실패하거나 하진 않겠지만 테스트 시간이 오래 걸린다는 단점이 있습니다.

`mock`객체를 사용하긴 했지만, 저희가 `Spring Security`를 사용하고 있어서 앞 단에 많은 필터체인을 거치기도 하고, `Dispatcher Servlet`, `tomcat` 등 **로직 테스트에 의미 없는 View 로직을 수행하고 있다고 생각해요.**

그래서 서비스 로직 테스트나 서비스단의 `validation` 테스트는 `mockmvc`를 사용하지 않는 `Service` 테스트로 작성하는 습관을 들이시면 더 좋을 것 같습니다!

2023-02-14 12:49 UTC, hyuunnn commented
```java
public interface SeminarRepository extends JpaRepository<Seminar, Long> {

  long virtualSeminarId = 1L;

  @Override
  default List<Seminar> findAll() {
    return findAllByIdIsNot(virtualSeminarId);
  }

  List<Seminar> findAllByIdIsNot(Long seminarId);
}
```

일반적으로 모든 데이터를 조회할 때 `findAll`을 사용하는데 virtual_seminar는 사용하지 않기 때문에 유연하게 만들어보고자 위와 같이 코드를 작성했었습니다.

그런데 기본적으로 제공하는 메서드 중에서 `findAll`이 아닌 `findById`, `findByOne`, `findAllById`를 사용했을 때는 virtual_seminar를 조회할 수 있게 됩니다.
이를 차단하기 위해 default 메서드로 다 선언하는게 맞을까요..?

2023-02-14 15:06 UTC, shkisme approved these changes
저도 많이 배워갑니다 👍👍

2023-02-14 15:54 UTC, merged