Feature/book 관련 entity repository 생성
KEEPER31337/Homepage-Back-R2 pull request #116
Opened 2023-02-17 14:34 UTC by JJimini

## 🔥 Related Issue

close: # 15

## 📝 Description

book 관련 db 수정 사항을 반영하여 마무리 하였습니다.

## ⭐️ Review

개강 싫어요...........

2023-02-18 04:31 UTC, shkisme reviewed
제가 만든 코드를 리뷰하니 기분이 이상하군요... 이제는 @JJimini 님이 맘껏 수정하시면 될 것 같네요 ㅎㅎ

2023-02-18 04:31 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/library/entity/Book.java
> +  private final List<BookBorrowInfo> bookBorrowInfos = new ArrayList<>();
이렇게 수정하게 된다면, 다음 테스트를 추가해보면 좋을 것 같네요.

- 책이 삭제되면, 빌린 책 정보도 삭제되는지 확인 (밑에 이 테스트가 작성되어 있던데 성공하는지 확인해보시면 좋을 것 같네요)

2023-02-18 12:07 UTC, gusah009 requested changes
수고 많으셨습니다! 커멘트 한 번 확인 부탁드려요~~

2023-02-18 12:07 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/library/entity/Book.java
> +  private final List<BookBorrowInfo> bookBorrowInfos = new ArrayList<>();
현경님 의견 좋은 것 같습니다! 👍👍

2023-02-18 12:07 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/library/entity/Book.java
> +  private final List<BookBorrowInfo> bookBorrowInfos = new ArrayList<>();
그렇게 된다면 `Book#addBookBorrowInfo`와 `BookBorrowInfo #registerBook` 메서드는 제거해주는 게 좋을 것 같아요!

2023-02-18 12:07 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/member/entity/Member.java
>    private final Set<MemberHasMemberJob> memberJob = new HashSet<>();
nit: 으윽 개행이 불편합니다..

2023-02-18 12:07 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/member/entity/Member.java
>    private final Set<MemberHasMemberJob> memberJob = new HashSet<>();
+) 회원이 탈퇴한다고 해서 그 회원이 책을 빌린 정보가 사라져도 될까요...?

2023-02-18 13:11 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/library/entity/Book.java
> +  private final List<BookBorrowInfo> bookBorrowInfos = new ArrayList<>();
네네 좋은 것 같아요!! 현경님 의견대로 수정해 보겠습니다!

2023-02-25 11:48 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/member/entity/Member.java
>    private final Set<MemberHasMemberJob> memberJob = new HashSet<>();
> +) 회원이 탈퇴한다고 해서 그 회원이 책을 빌린 정보가 사라져도 될까요...?

이 부분은 회의에서 이야기해봤는데, cascade 설정을 지금처럼 ALL로 두고 추후 개발 시 수정하는 것으로 마무리 지었습니다! 또한 나중에 잊지 않기 위해 해당 내용을 readme파일에 적어서 남겨두기로 하였습니다!!

2023-02-25 11:59 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/library/dao/BookRepositoryTest.java
> +          .build();
이 줄은 없어도 될 것 같습니다!

2023-02-25 11:59 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/library/README.md
> +하지만 멤버 탈퇴 시, 빌린 책 정보가 사라지면 안되므로(미납 기록이 있으면 회원 탈퇴가 되지 않도록 기능 추가 해야 함.) 추후 개발 시 이 점을 고려하여 수정 및 개발하여야 합니다.
멤버가 탈퇴할 때, 멤버의 빌린 정보가 있으면 아예 탈퇴가 되지 않도록 개발하면 문제가 없을 것 같기도 한데, 혹시 어떻게 생각하시나요? (제 생각이 맞을까요?? 😂)

2023-02-25 11:59 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/library/dao/BookRepositoryTest.java
> +      assertThat(bookBorrowInfoRepository.findAll()).doesNotContain(bookBorrowInfo);
이 `assertThat`도 의미없는 체크를 하고 있는 것 같아요!

2023-02-25 11:59 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/member/entity/Member.java
> +  }
연관관계 편의 메서드 좋아요 👍 
그런데 책을 반납할때 사용하는 편의 메서드도 있으면 좋겠습니다...!

`Member` 쪽의 `leave()` 메서드를 참고해보셔도 좋을 것 같아요!

2023-02-25 12:08 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/member/entity/Member.java
> +  }
넵넵 만들어보겠습니당

2023-02-25 12:12 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/library/README.md
> +하지만 멤버 탈퇴 시, 빌린 책 정보가 사라지면 안되므로(미납 기록이 있으면 회원 탈퇴가 되지 않도록 기능 추가 해야 함.) 추후 개발 시 이 점을 고려하여 수정 및 개발하여야 합니다.
> 멤버가 탈퇴할 때, 멤버의 빌린 정보가 있으면 아예 탈퇴가 되지 않도록 개발하면 문제가 없을 것 같기도 한데, 혹시 어떻게 생각하시나요? (제 생각이 맞을까요?? 😂)

네 저도 이게 맞다고 생각하는데, 지금은 엔티티 생성 단계이니 일단 ALL로 두고 추후 해당 기능을 개발할 때 수정하는게 어떨까 생각했습니다!

2023-02-25 12:58 UTC, shkisme approved these changes
수고하셨습니다!

2023-02-26 01:35 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/library/README.md
> +하지만 멤버 탈퇴 시, 빌린 책 정보가 사라지면 안되므로(미납 기록이 있으면 회원 탈퇴가 되지 않도록 기능 추가 해야 함.) 추후 개발 시 이 점을 고려하여 수정 및 개발하여야 합니다.
일단 `ALL`로 둔다는 건 굉장히 위험한 행동인 것 같습니다.

기획상 미납 기록이 있으면 회원이 탈퇴하지 못하도록 할거라면 `cascade`는 적용하지 않거나 `PERSIST`만 적용하는 것도 좋아보입니다!

2023-02-26 01:44 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/library/converter/BookDepartmentTypeConverter.java
> +public class BookDepartmentTypeConverter implements AttributeConverter<BookDepartmentType, String> {
`Converter`로직이 계속해서 반복되고 있네요 ㅎㅎ... @shkisme 이정도면 `ConverterUtil`로 빼서 중복 로직을 제거해도 좋을 것 같습니다.

2023-02-26 01:44 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/library/dao/BookRepositoryTest.java
> +    void should_deleteBookBorrowInfo_when_deleteBook() {
이 부분도 회원이 탈퇴했을 때와 비슷한 맥락인데, 책을 빌린 내역이 있는데 책 삭제가 가능한가요? (진짜 모름)

2023-02-26 01:47 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/library/README.md
> +하지만 멤버 탈퇴 시, 빌린 책 정보가 사라지면 안되므로(미납 기록이 있으면 회원 탈퇴가 되지 않도록 기능 추가 해야 함.) 추후 개발 시 이 점을 고려하여 수정 및 개발하여야 합니다.
> 일단 `ALL`로 둔다는 건 굉장히 위험한 행동인 것 같습니다.

동의합니다...! 👍

2023-02-26 01:50 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/library/converter/BookDepartmentTypeConverter.java
> +public class BookDepartmentTypeConverter implements AttributeConverter<BookDepartmentType, String> {
흠 그러네요! 이슈 파서 만들어보겠습니다~!

2023-02-26 02:27 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/library/README.md
> +하지만 멤버 탈퇴 시, 빌린 책 정보가 사라지면 안되므로(미납 기록이 있으면 회원 탈퇴가 되지 않도록 기능 추가 해야 함.) 추후 개발 시 이 점을 고려하여 수정 및 개발하여야 합니다.
수정하겠습니다....!

2023-02-26 15:52 UTC, shkisme reviewed
기획자분 답이 오시면, DB 변경사항이 또 생길 것 같네요!! 😥

2023-02-26 15:52 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/member/entity/Member.java
> +  @OneToMany(mappedBy = "member", cascade = PERSIST, orphanRemoval = true)
`orphanRemoval = true`도 제거해줘야 할 것 같아요! (안그러면 `member`가 삭제될 때 도서 정보가 다 날아가겠네요!) 그러면, 편의 메서드 `returns`도 사용하지 못하게 될 것 같습니다. 죄송합니다... ㅎ

2023-02-27 02:53 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/member/entity/Member.java
> +  @OneToMany(mappedBy = "member", cascade = PERSIST, orphanRemoval = true)
괜찮습니다ㅎㅎ `orphanRemoval = true` 는 제거해두겠습니다

2023-02-27 12:31 UTC, JJimini commented on src/test/java/com/keeper/homepage/domain/library/dao/BookRepositoryTest.java
> +    void should_deleteBookBorrowInfo_when_deleteBook() {
미납 내역이 있으면 도서를 삭제 하면 안되므로, `Book`의 `cascade = REMOVE` 부분을 삭제하는 것으로 수정하려 합니다!!

2023-02-27 13:38 UTC, JJimini commented
이 pr은 db가 수정되면, 다시 작업해서 re request 요청하겠습니다!!

2023-03-01 09:14 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/library/converter/BookBorrowStatusTypeConverter.java
> +public class BookBorrowStatusTypeConverter implements AttributeConverter<BookBorrowStatusType, String> {
`ConverterUtil` 얼른 제작해야겠네요... 😂

2023-03-01 09:14 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/library/dao/BookRepositoryTest.java
> +    private List<String> getStatuses(List<BookBorrowStatus> bookBorrowStatuses) {
Nit: `getStatuses` 복수형으로 사용하신 이유가 있나요?

2023-03-01 09:14 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/library/README.md
> +하지만 멤버 탈퇴 시, 빌린 책 정보가 사라지면 안되므로(미납 기록이 있으면 회원 탈퇴가 되지 않도록 기능 추가 해야 함.) 추후 개발 시 이 점을 고려하여 수정 및 개발하여야 합니다.
리드미도 수정해주시면 감사할 것 같습니다!

2023-03-01 09:14 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/member/entity/Member.java
> +  }
`BorrowStatus`가 `not null` 이던데 값을 넣어줘야 할 것 같아요!

2023-03-01 09:20 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/library/dao/BookRepositoryTest.java
> +    }
Nit: 메서드 이름을 `getStatuses` , 복수형으로 사용하신 이유가 있나요? 다른건 리스트를 반환해서 괜찮은데 이건 String을 반환하고 있어서요!

2023-03-01 09:22 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/member/entity/Member.java
> +  }
넵넵

2023-03-01 09:23 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/library/README.md
> +하지만 멤버 탈퇴 시, 빌린 책 정보가 사라지면 안되므로(미납 기록이 있으면 회원 탈퇴가 되지 않도록 기능 추가 해야 함.) 추후 개발 시 이 점을 고려하여 수정 및 개발하여야 합니다.
`Book` 에 `cascade = REMOVE` 설정 삭제한 것에 대해 추가하라는 말씀이신거죠?!

2023-03-01 09:25 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/library/README.md
> +하지만 멤버 탈퇴 시, 빌린 책 정보가 사라지면 안되므로(미납 기록이 있으면 회원 탈퇴가 되지 않도록 기능 추가 해야 함.) 추후 개발 시 이 점을 고려하여 수정 및 개발하여야 합니다.
흠.. 리드미를 아예 삭제하는 것도 괜찮을 것 같습니다!! (이 단계에서 기록해 둘 게 없는 것 같아서요!)

제 생각입니다!!

2023-03-01 09:30 UTC, JJimini commented on src/test/java/com/keeper/homepage/domain/library/dao/BookRepositoryTest.java
> +    }
엇 실수입니다,,, 고치겠습니다..!

2023-03-01 09:33 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/library/README.md
> +하지만 멤버 탈퇴 시, 빌린 책 정보가 사라지면 안되므로(미납 기록이 있으면 회원 탈퇴가 되지 않도록 기능 추가 해야 함.) 추후 개발 시 이 점을 고려하여 수정 및 개발하여야 합니다.
> 흠.. 리드미를 아예 삭제하는 것도 괜찮을 것 같습니다!! (이 단계에서 기록해 둘 게 없는 것 같아서요!)
> 
> 제 생각입니다!!

넵 저도 이게 좋다고 생각합니다!

2023-03-02 00:00 UTC, hyuunnn approved these changes
수고하셨습니다~~

2023-03-02 00:00 UTC, hyuunnn commented on src/test/java/com/keeper/homepage/domain/library/dao/BookRepositoryTest.java
> +    }
`bookDepartmentTypes` 변수에 `departmentTypes` 데이터를 넣은 후에 `getIds`와 `getNames` 메서드로 데이터를 비교하는데 for문으로 다시 비교 할 필요가 있는지 궁금하네요!

필요가 없다면 `BookDepartmentType.values()`를 `Arrays.stream()` 안에 넣어도 좋을 것 같아요.

2023-03-03 04:08 UTC, JJimini commented on src/test/java/com/keeper/homepage/domain/library/dao/BookRepositoryTest.java
> +    }
넵넵 수정했습니다!

2023-03-03 10:35 UTC, merged