Feature/static write 관련 entity repository 생성 #11
KEEPER31337/Homepage-Back-R2 pull request #24
Opened 2023-01-21 05:39 UTC by shkisme

## 🔥 Related Issue

close: #11

## 📝 Description

- `StaticWriteContent`, `StaticWriteSubtitleImage`, `StaticWriteTitle`의 Entity, Repository를 생성했습니다.
- `StaticWriteContent`, `StaticWriteSubtitleImage`, `StaticWriteTitle`의 Repository Test 코드를 작성했습니다.

## ⭐️ Review

연관관계가 적은 Static Write (about) 부터 진행해봤습니다!
리뷰 부탁드립니다 ! 🙇‍♀️

2023-01-21 10:39 UTC, gusah009 requested changes
수고하셨습니다! 👍👍👍

2023-01-21 10:39 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/about/entity/StaticWriteTitle.java
> +  private String title;
`Column`에 정확하게 `nullable`이나 `updatable`을 기재한 부분 좋습니다!! 👍👍

2023-01-21 10:39 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/about/entity/StaticWriteTitle.java
> +  private String type;
`Enumerate`를 활용해 `BasicStaticWriteTitleType`으로 타입을 지정하시는 건 어떨까요?

+ `Enumerate`로 지정하신다면 DB의 데이터와 일치하는지 확인하는 테스트 코드도 작성하시면 좋을 것 같습니다!

2023-01-21 10:39 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/about/entity/StaticWriteTitle.java
> +    private final String type;
개행의 이유가 있을까요?

2023-01-21 10:39 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/about/entity/StaticWriteTitle.java
> +    }
접근 제어자가 없는 이유가 있을까요?

2023-01-21 10:39 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/about/StaticWriteTestHelper.java
> +  }
`TestHelper` 좋습니다!! 혹시 여유가 된다면 [postTestHelper.java](https://github.com/Busan-Dinosaur/FoodBowl-Server/blob/develop/src/test/java/com/dinosaur/foodbowl/domain/post/PostTestHelper.java) 코드를 참고하셔서 빌더로 만들어 보시는 것도 추천드립니다! (강요)

2023-01-21 10:39 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/about/dao/StaticWriteRepositoryTest.java
> +    @DisplayName("기본 타이틀 타입 테스트")
**`"기본 타이틀 타입 테스트"`** 보다 `should_XXX_when_XXX` 문법을 따라 **`"어떤 조건일 때 어떤 결과를 뱉는다"`** 식으로 테스트명을 작성하시면 더 좋을 것 같습니다!

2023-01-21 10:39 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/about/dao/StaticWriteRepositoryTest.java
> +    @DisplayName("기본 타이틀 타입 테스트")
테스트 작성 👍👍

2023-01-21 12:23 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/about/entity/StaticWriteTitle.java
> +  private String type;
이게 타이틀이 고정되어 있는 건 줄 알았는데 어드민이 타이틀과 타입을 수정하는 기능이 있더라구요... !

2023-01-21 12:31 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/about/entity/StaticWriteTitle.java
> +    }
private 접근 제어자가 있으나 없으나 마찬가지라서 (enum의 생성자는 private만 허용) 빼고 적었습니다 !

2023-01-21 12:45 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/about/entity/StaticWriteTitle.java
> +  private String type;
저는 타이틀이 고정인 줄 알았는데 찾아보니까 관리자가 타이틀을 수정하는 API가 존재하더라구요...! 프론트에 연락해서 해당 기능 사용하는지 여쭤보고 수정을 해야 할 것 같습니다! 😓

2023-01-21 12:45 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/about/entity/StaticWriteTitle.java
> +  private String type;
저는 타이틀이 고정인 줄 알았는데 찾아보니까 관리자가 타이틀을 수정하는 API가 존재하더라구요...! 프론트에 연락해서 해당 기능 사용하는지 여쭤보고 수정을 해야 할 것 같습니다! 😓

2023-01-21 21:44 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/about/entity/StaticWriteTitle.java
> +  private String type;
아하 수정할 수 있으면 `String`이 좋겠네요..!! 👍👍

2023-01-23 07:20 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/about/StaticWriteTestHelper.java
> +  }
오... 이거 현재 책에서 공부하고 있는 dsl 패턴이군요... 그런데 StaticWriteHelper 에서 만들어 보니 뭔가.. 코드가 복잡해지는 느낌이... 요거 공부 좀 더해서 꼭 만들어보겠습니다 !

2023-01-23 07:21 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/about/entity/StaticWriteTitle.java
> +  private String type;
프론트 분께 여쭤보니 타이틀이 수정될 일은 없어서 고정으로 가도 된다고 합니다 ! 이에 맞춰 수정하였습니다!

2023-01-24 01:32 UTC, gusah009 requested changes
커밋 메시지에도 마크다운 형식이 적용되네요?? 와우 👍👍

고생하셨습니다! 커멘트 한 번 확인 부탁드려요~!

2023-01-24 01:32 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/about/dao/StaticWriteContentRepository.java
> +  Optional<List<StaticWriteContent>> findAllByStaticWriteSubtitleImage_StaticWriteTitle_Type(
@shkisme `List`로 반환하고 있어서 `Optional`로 반환할 필요는 없을 것 같습니다!

2023-01-24 01:32 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/about/entity/StaticWriteTitle.java
> +    history(4, "동아리 연혁", "history");
왜 소문자로 바꿨는지 알 수 있을까요??

2023-01-24 01:32 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/about/dao/StaticWriteRepositoryTest.java
> +          .stream(StaticWriteTitleType.values()).toList();
모두 `given`으로 묶인다면 개행 없이 작성하는 것도 좋을 것 같습니다!

2023-01-24 01:32 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/about/dao/StaticWriteRepositoryTest.java
> -    @DisplayName("타이틀 저장 테스트")
60d99b878e65221bf46c3007352674573745d05e 저장 수정이 백엔드상에서 안되는 쪽으로 바뀌었나보네요! 좋습니다!!

2023-01-24 01:32 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/about/dao/StaticWriteRepositoryTest.java
> +    void should_allStaticWriteTitleExist_when_givenStaticWriteTitleTypeEnum() {
👍👍👍

2023-01-24 01:32 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/about/dao/StaticWriteRepositoryTest.java
> +          .findById(staticWriteSubtitleImage.getId());
타입이 너무 길다 싶으면 아래와 같이 바꾸는 것도 추천드립니다!

```java
final var findStaticWriteSubtitleImage = staticWriteSubtitleImageRepository
.findById(staticWriteSubtitleImage.getId());
```

2023-01-24 01:33 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/about/dao/StaticWriteRepositoryTest.java
> +          .stream(StaticWriteTitleType.values()).toList();
뒷 커밋에서 수정했었네요!! 😅

2023-01-24 01:38 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/about/dao/StaticWriteContentRepository.java
> +  Optional<List<StaticWriteContent>> findAllByStaticWriteSubtitleImage_StaticWriteTitle_Type(
헐.. 그러네요 너무 Optional을 생각없이 쓴 것 같습니다! 감사합니다

2023-01-24 01:42 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/about/entity/StaticWriteTitle.java
> +    history(4, "동아리 연혁", "history");
DB에는 `type` 이 소문자로 들어 있어서 이렇게 바꿨습니다.. 대문자로 하면 다르다고 나오더라구요 ㅜㅜ 대문자를 소문자로 변경해주는 그런 방법이 있나요? 찾아보겠습니다 !

2023-01-24 01:47 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/about/entity/StaticWriteTitle.java
> +    history(4, "동아리 연혁", "history");
https://studyandwrite.tistory.com/496 이 블로그에서 처럼 컨버터를 활용하는 방법도 있을 것 같네요!

2023-01-24 01:54 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/about/dao/StaticWriteRepositoryTest.java
> +          .findById(staticWriteSubtitleImage.getId());
wow.. 이렇게 타입추론을 사용할 수도 있군요.. ! ! ! 가능하다는 걸 알고는 있었는데 자바라서 선뜻 손이 가지 않던.. 

![image](https://user-images.githubusercontent.com/92802207/214196815-6504a06f-67ba-4ba8-8986-cced12cca41f.png)

심지어 `IntelliJ`가 친절하게 뭔지도 알려주네요👍 앞으로 상황에 따라 적극 활용 해보겠습니다 !

2023-01-24 02:32 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/about/entity/StaticWriteTitle.java
> +    history(4, "동아리 연혁", "history");
감사합니다~! 컨버터로 수정하였습니다! 👍

2023-01-24 06:11 UTC, gusah009 approved these changes
👍👍 수고 많으셨습니다!

2023-01-24 06:59 UTC, hyuunnn approved these changes

2023-01-24 06:59 UTC, hyuunnn commented on src/main/java/com/keeper/homepage/domain/about/entity/StaticWriteTitle.java
> +    }
lombok `RequiredArgsConstructor` 쓰면 더 좋을 것 같습니다..!

2023-01-24 07:39 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/about/entity/StaticWriteTitle.java
> +    }
좋습니다 ~! 👍

2023-01-24 07:53 UTC, merged