Feature/Election 관련 entity repository 생성
KEEPER31337/Homepage-Back-R2 pull request #264
Opened 2023-08-02 15:24 UTC by JJimini

## 🔥 Related Issue

> close: #12

## 📝 Description

> election 관련 entity와 repository입니다!

## ⭐️ Review Request

> 드디어 카테캠 마무리..😄

2023-08-03 12:23 UTC, shkisme approved these changes
굿굿 !! 수고 많으셨어용 👍👍👍

2023-08-03 12:23 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/election/entity/Election.java
> +    this.registerTime = registerTime;
`registerTime`은 파라미터로 받지 않고, `LocalDateTime.now()`로 바로 지정해줄 수 있을 것 같아요!

```java
this.registerTime = LocalDateTime.now();
```

2023-08-03 12:23 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/election/entity/ElectionCandidate.java
> +    this.registerTime = registerTime;
위 코멘트와 동일합니다~!

2023-08-03 12:23 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/election/dao/ElectionRepositoryTest.java
> +      Election getVoters = electionRepository.getById(election.getId());
테스트에서 `getById()` 사용 좋은 것 같네요~! 👍

그런데 찾아보니 `getById()` 대신 `getReferenceById()`를 사용하는 것을 권장한다고 합니다!
<img width="663" alt="image" src="https://github.com/KEEPER31337/Homepage-Back-R2/assets/92802207/3ad3cf5b-cdf6-46f1-81ec-4b9aeb6c0395">

2023-08-03 13:28 UTC, JJimini commented on src/test/java/com/keeper/homepage/domain/election/dao/ElectionRepositoryTest.java
> +    public void getVotersInElection() throws Exception {
헉 그렇겠네요...!

2023-08-05 04:31 UTC, gusah009 requested changes
아이고 리뷰가 늦었습니당...! 확인 부탁드려요~~ 수고많으셨습니다 👍👍

2023-08-05 04:31 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/election/entity/ElectionVoter.java
> +  @GeneratedValue(strategy = IDENTITY)
여기서 `@GeneratedValue(strategy = IDENTITY)`의 용도는 뭘까용?

2023-08-05 04:31 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/election/ElectionVoterTestHelper.java
> +          .isVoted(isVoted)
위에 컬럼 설정할 땐 `@Column(name = "is_voted", nullable = false)`로 `nullable = false` 설정하셨는데, 여기선 null일수도 있을 것 같아요~

2023-08-05 04:31 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/election/dao/ElectionRepositoryTest.java
> +}
newline 부탁드려용

2023-08-05 04:31 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/election/dao/ElectionVoterRepository.java
> +      boolean isVoted);
`Member`와 `Election`이 특정됐는데 `List`로 올 일이 있나요..?

2023-08-05 04:31 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/election/dao/ElectionRepositoryTest.java
> +          .build();
```suggestion
      ElectionVoter electionVoter = electionVoterTestHelper.builder()
          .isVoted(false)
          .build();
```

2023-08-05 04:31 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/election/dao/ElectionRepositoryTest.java
> +      Election getVoters = electionRepository.getReferenceById(election.getId());
repository에서 `getById`, `findById`, `getReferenceById`의 차이가 뭘까요..? (진짜모름)

2023-08-05 07:14 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/election/dao/ElectionRepositoryTest.java
> +}
인텔리제이에서 자동으로 end of file new line 추가하도록 설정할 수 있습니다!

https://www.notion.so/End-of-file-new-line-defa54bc317f4f95b75496bbc5584d0e?pvs=4

2023-08-05 09:12 UTC, JJimini commented on src/test/java/com/keeper/homepage/domain/election/dao/ElectionRepositoryTest.java
> +      Election getVoters = electionRepository.getReferenceById(election.getId());
제가 알기로는 `getById`는 프록시만 반환하기 때문에 실제 DB에 직접적인 요청이 없고, `findById`는 실제 DB에 요청이 있는 것으로 알고 있습니다. 그래서 `getById`가 성능 상으로 조금 더 좋다고 알고 있습니다! (특정 엔티티의 ID 값만 필요한 경우)

https://creampuffy.tistory.com/162

2023-08-05 09:23 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/election/entity/ElectionVoter.java
> +  @GeneratedValue(strategy = IDENTITY)
기본 키 값을 자동으로 생성해주는 거 아닌가요...? ElectionVoter의 경우 복합키를 가져서 `voter_id`와 `election_id`에 모두  `@GeneratedValue(strategy = IDENTITY)`를 설정했던 것으로 기억합니다!

2023-08-05 12:19 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/election/entity/ElectionVoter.java
> +  @GeneratedValue(strategy = IDENTITY)
아하 그런데 `Member`랑 `Election`의 id를 자동으로 생성해 줄 필요가 있나요?? `ElectionVoter` 만들 때 `Member`, `Election`  id는 명시해 줄 것 같아서요~

2023-08-05 14:01 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/election/entity/ElectionVoter.java
> +  @GeneratedValue(strategy = IDENTITY)
오! 그렇네용!!!

2023-08-06 03:02 UTC, shkisme approved these changes
빠른 반영 너무 좋습니당~~ ✨ 굿굿굿

2023-08-06 03:14 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/election/dao/ElectionVoterRepository.java
> +  ElectionVoter findByMemberAndElectionAndIsVoted(Member member, Election election, Boolean isVoted);
고민했었던 부분인데, 역시 이렇게 하는 게 더 좋군요!

2023-08-06 03:25 UTC, gusah009 approved these changes
수고많으셨습니다~~ 👍👍

2023-08-06 03:25 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/election/dao/ElectionVoterRepositoryTest.java
> +          member, election, true);
`votedVoters` 복수형 쓰여져있는것같아요~

2023-08-06 03:34 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/election/dao/ElectionVoterRepositoryTest.java
> +          .build();
앗 밑에 코드에서 member와 election이 쓰이고 있군용..ㅎㅎ 그렇다면 놔두어도 괜찮겠습니다! 😄

2023-08-06 03:40 UTC, JJimini commented on src/test/java/com/keeper/homepage/domain/election/dao/ElectionVoterRepositoryTest.java
> +          .build();
이 부분은
```
      Optional<ElectionVoter> votedVoters = electionVoterRepository.findByMemberAndElectionAndIsVoted(
          member, election, true);
```

이 부분에서 `member` 와 `election`이 필요한 것 같아서, 그대로 두어도 될 것 같은데 괜찮을까요?!

2023-08-06 03:42 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/election/dao/ElectionVoterRepositoryTest.java
> +          .build();
넵넵 아래의 코드에서 쓰인다면 두어도 괜찮을 것 같네요~~!! 안쓰이는 줄 알았습니다 😅 (안쓰인다면 build()에서 알아서 생성해주니까욤!)

2023-08-06 13:24 UTC, merged