Feature/첨부파일 목록 조회 api 분리
KEEPER31337/Homepage-Back-R2 pull request #271
Opened 2023-08-06 16:14 UTC by shkisme

## 🔥 Related Issue

> close: #없음

## 📝 Description

게시글 조회 응답으로 첨부파일을 반환하는 걸 빼고, 첨부파일 목록 조회 api를 따로 만들었습니다.
대신 첨부파일 목록을 조회할 때 시험게시판일 경우 회원의 포인트가 `10000`포인트씩 차감됩니다.
그리고 자잘한 리팩토링 했습니다!

## ⭐️ Review Request

> 리뷰어에게 전달하고 싶은 내용을 적어주세요.

2023-08-07 08:16 UTC, gusah009 requested changes
commit 단위로 나뉘어져 있어서 보기 쉬웠습니다~ 커멘트 확인 부탁드려요 ㅎㅎ

2023-08-07 08:16 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/post/application/PostService.java
> +      member.minusPoint(EXAM_READ_DEDUCTION_POINT);
이러면 모든 회원 중에 맨 처음에 파일을 본 회원의 포인트만 차감되는거 아닌가요?? `post`의 `isRead` 필드는 모든 member에게 동일하게 적용되는 것 같아요~

2023-08-07 08:32 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/post/application/PostService.java
> +      member.minusPoint(EXAM_READ_DEDUCTION_POINT);
그렇네요....... 바보였다 😂

테이블을 하나 더 두는게 맞겠네요..

2023-08-08 10:40 UTC, gusah009 approved these changes
아예 테이블을 하나 더 만드셨군요~ 고생하셨습니당~

2023-08-08 10:40 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/post/application/PostService.java
> +    if (post.isCategory(시험게시판) && !member.hasRead(post)) {
`member.hasRead()`보단 `member.isRead()`가 더 읽기 쉬운 것 같아용

2023-08-10 02:48 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/post/application/PostService.java
> +    if (post.isCategory(시험게시판) && !member.hasRead(post)) {
저도 `isRead`가 더 읽기 쉬운 것 같네요 ㅎㅎ 반영하겠습니다

2023-08-10 02:53 UTC, merged