feat: 족보 열람시 차감된 포인트 로그 생성 코드 추가
KEEPER31337/Homepage-Back-R2 pull request #286
Opened 2023-08-13 02:56 UTC by shkisme

## 🔥 Related Issue

> close: #없음

## 📝 Description

<img width="739" alt="image" src="https://github.com/KEEPER31337/Homepage-Back-R2/assets/92802207/cee43230-6861-46a7-8cad-f0b21bd9127f">

기획서 보니까 족보 열람할때 차감한 포인트에 대한 로그도 남겨줘야겠더라구요! 해당 작업 수행했습니다.

## ⭐️ Review Request

> 리뷰어에게 전달하고 싶은 내용을 적어주세요.

2023-08-13 05:39 UTC, gusah009 requested changes
포인트 로그 서비스가 결국 포인트 변경내역을 기록하는 것 같은데, member에서 addPoint, minusPoint 할 때 기록해주는건 어떨까요? 로깅 로직이랑 실제 포인트 전달 로직이 따로 있는게 이렇게 실수를 유발할 수 있을 것 같아서요~

혹시 가능할까요??

2023-08-13 14:38 UTC, shkisme commented
> 포인트 로그 서비스가 결국 포인트 변경내역을 기록하는 것 같은데, member에서 addPoint, minusPoint 할 때 기록해주는건 어떨까요? 로깅 로직이랑 실제 포인트 전달 로직이 따로 있는게 이렇게 실수를 유발할 수 있을 것 같아서요~

확실히 코드를 빼먹거나 음수로 저장을 안하는 등의 실수 여지가 높은 것 같습니다! 수정하겠습니다 👍👍

2023-08-14 23:55 UTC, gusah009 approved these changes
수고하셨습니다~~

2023-08-15 01:37 UTC, JJimini approved these changes
수고하셨습니당!

2023-08-15 01:39 UTC, 02ggang9 approved these changes
수고하셨습니다!!!

2023-08-15 02:30 UTC, merged