Feature/선거 생성 기능 구현
KEEPER31337/Homepage-Back-R2 pull request #289
Opened 2023-08-13 08:23 UTC by JJimini

## 🔥 Related Issue

> close: #251

## 📝 Description

> 선거 생성 기능을 구현했습니다!

## ⭐️ Review Request

> 오늘의 tmi : 오늘 치고 온 한국사 시험 2점 차이로 2급 받음

2023-08-13 09:09 UTC, gusah009 requested changes
2점차이라니... 🥲

2023-08-13 09:09 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/election/application/AdminElectionService.java
> +    }
이 부분이 이해가 안되는데, 생성할 때 선거가 활성화되지 않으면 생성을 못하는건가요?

그럼 항상 `true`로 넘겨줘야하는걸까요?

2023-08-13 11:08 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/election/application/AdminElectionService.java
> +    }
그렇네요....이거 선거 생성 기능이었죠.... 제가 왜 저렇게 생각했을까요.... 바로 수정하겠습니다ㅠㅠ😱

2023-08-13 11:36 UTC, gusah009 approved these changes
수고하셨습니당~ 👍👍👍

2023-08-13 14:03 UTC, shkisme approved these changes
굿굿! 수고하셨습니다~~

2023-08-14 01:19 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/election/api/AdminElectionController.java
> +@RequestMapping("/elections")
넵 좋습니다~! 임원진 투표 페이지도 있어서 `admin`을 붙이는 게 더 좋겠네용!

2023-08-14 01:25 UTC, merged

2023-08-14 01:51 UTC, JJimini commented
@shkisme test가 수정이 안되어서 오류나는군요ㅠㅠ 이 부분은 선거 삭제 기능 만들 때 수정해서 추가하겠습니다ㅠㅠ!
다음부터는 test 꼭 확인하고 pr 닫겠습니다......