Feature/포인트 기능 구현
KEEPER31337/Homepage-Back-R2 pull request #292
Opened 2023-08-13 14:19 UTC by 02ggang9

## 🔥 Related Issue

> close: #

## 📝 Description

> 수행한 작업을 설명해주세요.
포인트 선물 기능과 포인트 내역 조회 기능을 만들었습니다.

## ⭐️ Review Request

> 리뷰어에게 전달하고 싶은 내용을 적어주세요.
잘 부탁드리겠습니다.. OTL

2023-08-14 02:47 UTC, shkisme commented on src/docs/asciidoc/keeper.adoc
> +== *POiNT API*
PoiNT -> POINT 😁

2023-08-14 02:47 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/member/entity/Member.java
> +
위에 addPoint 메서드가 있는 것 같아요 ㅎㅎ

2023-08-14 02:47 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/point/application/GivePointService.java
> +    pointLogService.create(receiver, null, point, message);
로그 남기는 건 member의 minusPoint, addPoint 메서드에서 해주는 게 좋은 것 같습니다! 

https://github.com/KEEPER31337/Homepage-Back-R2/pull/286/commits/6e39552ef6e296ebd62be4d07872731a47d93ae2

위 PR의 커밋에서의 변경점을 참고해주시면 될 것 같고, 위 PR 머지되면 최신 develop을 받아서 고쳐주시면 될 거 같아요!

2023-08-14 02:47 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/point/application/PointLogService.java
> +  }
회원별 모든 포인트 로그를 불러오는 api가 필요할 것 같아요 ㅎㅎ
지금은 그냥 모든 포인트 로그를 불러오는 것 같습니다!

2023-08-14 03:13 UTC, 02ggang9 commented on src/docs/asciidoc/keeper.adoc
> +== *POiNT API*
수정했습니다. 감사합니다~!

2023-08-14 03:15 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/member/entity/Member.java
> +
아앗.. 똑바로 못 살펴봤네요..ㅠㅠ 수정했습니다!!

2023-08-14 03:17 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/point/application/GivePointService.java
> +    pointLogService.create(receiver, null, point, message);
확인했습니다..! 감사합니다~~

2023-08-14 03:37 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/point/application/PointLogService.java
> +  }
수정했습니다..!!! 감사합니다~

2023-08-15 01:28 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/point/application/GivePointService.java
> +    Member receiver = memberFindService.findById(receiverId);
감사합니닷!!

2023-08-15 01:29 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/point/api/PointController.java
> +    givePointService.givePoint(member.getId(),
맞네용.. 바로 바꾸겠습니다..!!

2023-08-15 01:33 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/point/application/PointLogService.java
> +    return pointLogRepository.findAllByMemberId(pageable, findMemberId);
아!! 그렇군요! JWT랑 작성해주신 코드 공부해보도록 하겠습니다.. 감사합니다!!

2023-08-15 01:37 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/point/dto/response/FindAllPointLogsResponse.java
> +public class FindAllPointLogsResponse {
수정했습니다 감사합니다!!

2023-08-15 01:37 UTC, 02ggang9 commented on src/test/java/com/keeper/homepage/domain/point/application/PointLogServiceTest.java
> +
삭제했습니다!! 감사합니다..!!!

2023-08-15 04:40 UTC, shkisme approved these changes
굿굿굿굿 👍👍👍 수고 많으셨습니다~

2023-08-15 04:40 UTC, shkisme commented on src/docs/asciidoc/keeper.adoc
> +>>>>>>> develop
수정이 필요할 것 같습니다~

2023-08-15 04:40 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/point/application/GivePointService.java
> +    receiver.addPoint(point, message);
👍👍👍👍

2023-08-15 04:40 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/point/dto/request/presentPointRequest.java
> +  private String message;
보낼 메세지는 null이여도 괜찮은가욥?

2023-08-15 04:40 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/point/api/PointController.java
> +
컨트롤러 단에 `@Validated` 붙여줘야 `@PositiveOrZero` 같은 어노테이션들의 검증이 될 것 같아요~!

2023-08-15 08:09 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/point/dto/request/presentPointRequest.java
> +  private String message;
제가 생각하기엔 메시지가 없어도 괜찮다고 생각했습니다!!

2023-08-15 08:09 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/point/api/PointController.java
> +
수정했습니다!! 감사합니다~~

2023-08-15 08:38 UTC, shkisme requested changes
커멘트 반영해주시고 재 리뷰요청 해주세욥~

2023-08-15 08:38 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/point/application/GivePointService.java
> +    receiver.addPoint(point, message);
아래처럼 구현해주시길 바랍니다! ⭐️

**보낸 메시지가 없을 경우**
포인트 받는 사람 : `포인트 선물 획득`
포인트 보낸 사람 : `포인트 선물 차감`
**보낸 메시지가 있을 경우**
포인트 받는 사람 : `포인트 선물 획득 - {보낸 메시지}`
포인트 보낸 사람 : `포인트 선물 차감 - {보낸 메시지}`

2023-08-15 12:00 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/point/application/GivePointService.java
> +    receiver.addPoint(point, message);
수정했습니다~! 감사합니당!!

2023-08-15 12:08 UTC, shkisme approved these changes
수고하셨습니다~

2023-08-15 12:08 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/point/application/GivePointService.java
> +  private static final String RECEIVERDEFAULTMESSAGE = "포인트 선물 흭득";
`_` 로 단어를 구분해주시면 가독성이 높아질 것 같습니다 ㅎㅎ
`GIVER_DEFAULT_MESSAGE`

2023-08-15 12:12 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/point/application/GivePointService.java
> +  private static final String RECEIVERDEFAULTMESSAGE = "포인트 선물 흭득";
수정했습니다..!! 감사합니다~

2023-08-16 10:25 UTC, merged