feat: 회원 프로필 조회 기능 구현 및 테스트 코드 작성
KEEPER31337/Homepage-Back-R2 pull request #302
Opened 2023-08-16 08:25 UTC by 02ggang9

## 🔥 Related Issue
포맷팅 관련 때문에 revert랑 rebase를 처음 시도했다가 제대로 꼬였다 생각해서 새로 브랜치를 파게됐습니다. 죄송합니다 ㅠㅠ..

## 📝 Description
회원 프로필 조회 기능을 구현과 테스트 코드 작성을 완료 했습니다.

## ⭐️ Review Request
머지된 후 로직이 많이 바뀐거 같습니다! follower 는 직접 리포지토리에서 가져오고 스트림 돌면서 간단하게 해결했지만 followee 같은 경우에는 기능은 구현됐지만 Member와 Friend를 왔다갔다 하는 안좋은 코드가 완성된거 같습니다..! 아직 JPA를 완전히 이해못하고 급하게 배웠던게 여기서 터지고 마네요....ㅠㅠ 

한번 코드 살펴봐주시고 개선할 부분 알려주시면 정말 감사하겠습니다..!!

2023-08-16 08:31 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/member/dto/response/memberProfile/MemberProfileResponse.java
> +  }
이 부분과 위 부분의 코드를 어떻게 개선할지 정말 고민입니다..ㅠㅠ

2023-08-16 08:31 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/member/dto/response/memberProfile/MemberFolloweeResponse.java
> +
이 부분과 아래 부분의 코드가 왔다갔다 참고한다고 생각해서 어떻게 개선하면 좋을까요..??

2023-08-16 10:18 UTC, shkisme reviewed
굿입니다 👍👍👍 제 생각 커멘트로 남겨두었습니다!

2023-08-16 10:18 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/member/dto/response/memberProfile/MemberProfileResponse.java
> +        .followee(getFollowee(member))
`getFollower`에도 `member`를 인자로 넘겨 팔로워를 구할 수 있을 것 같습니다!

2023-08-16 10:18 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/member/dto/response/memberProfile/MemberProfileResponse.java
> +        .followee(getFollowee(member))
혹시 `Member` 엔티티에 `getFollwer`와 `getFollowee` 메서드를 추가해보는 건 어떨까요?

```java
List<Member> getFollower(){
...
}
```

2023-08-16 10:18 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/member/dto/response/memberProfile/MemberProfileResponse.java
> +  }
잘 하신 것 같은데욥?! 👍👍👍

2023-08-16 10:18 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/member/dto/response/memberProfile/MemberFolloweeResponse.java
> +
혹시 어떤 부분이 왔다갔다 참고하게 되는 부분인지 조금 더 설명 부탁드려도 될까요? 🙂

2023-08-16 10:57 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/member/api/MemberController.java
> +      @PathVariable @PositiveOrZero long memberId
넵넵 맞습니다!!

2023-08-16 10:57 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/member/api/MemberController.java
> +    );
아.. 이건 새벽에 컨트롤러에서 여러가지 시도를 하다가 저렇게 됐습니다 ㅠㅠ.. 지금은 수정되었습니다..!! 감사합니다

2023-08-16 10:57 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/member/dto/response/memberProfile/MemberFolloweeResponse.java
> +public class MemberFolloweeResponse {
처음에는 MemberFollowResponse로 통일을 하려고 Dto로 변환하는 로직을 통일화 하는 방법을 생각하지 못했습니다... 한번 다시 생각해보도록 하겠습니다..!

2023-08-16 10:57 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/member/dto/response/memberProfile/MemberFolloweeResponse.java
> +
Follower 같은 경우는 리포지토리에서 Friend를 찾고 .map(Friend::getFollower) 이렇게 해서 Member를 가져오고 .getRealName() 으로 이름을 찾아서 한 방향으로 간다는 느낌을 받았는데
Followee 같은 경우에는 Member에서 member.getFollower() 이렇게 해서 Friend를 가져오고 Member의 이름을 찾기 위해 다시 Friend에서 friend.getFollowee()로 Member로 돌아가서 이름을 찾아서 한바퀴 빙 도는 느낌을 받았습니다..ㅠㅠ

2023-08-16 10:57 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/member/dto/response/memberProfile/MemberProfileResponse.java
> +        .followee(getFollowee(member))
혹시 getFollower에 Member 인자로 넘길 시 어떻게 로직을 처리하면 좋을까요..? ㅠㅠ 
사실 어제 getFollower랑 getFollwee 둘 다 위에서 말씀해주신대로 공통 Response로 묶어서 해보려고 했는데 getFollowee 같은 경우에는 원하는 결과값이 나왔지만 getFollower는 Member를 못가져오거나 제 자신을 가져와서 Response도 분리하고 Follower는 Friend를 인자로 넘기는 방식을 택했습니다..!

2023-08-16 13:33 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/member/dto/response/memberProfile/MemberProfileResponse.java
> +  }
followee가 해당 멤버가 팔로우한 사람입니다!

2023-08-16 13:39 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/member/application/MemberService.java
> +    return MemberProfileResponse.from(findMember, findAllFollowers);
좋은 글 감사합니다!! 네이밍할 때마다 헷갈렸는데 정리가 되는 느낌입니다....!!!

2023-08-16 13:39 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/member/dto/response/memberProfile/MemberProfileResponse.java
> +  }
수정해보도록 하겠습니다!! 감사합니다~~

2023-08-17 05:09 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/member/dto/response/memberProfile/MemberFolloweeResponse.java
> +
아하! 레포지토리에서 찾는 방법도 있겠지만 member.getFollowee()와 member.getFollower()로 Friend를 바로 가져올 수 있을 것 같습니다!!

https://github.com/KEEPER31337/Homepage-Back-R2/blob/develop/src/test/java/com/keeper/homepage/domain/member/application/MemberServiceTest.java

제가 팔로우, 언팔로우 테스트 할 때 만든 테스트 코드인데 참고가 되실까 하여 링크 첨부합니당!

2023-08-17 05:13 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/member/dto/response/memberProfile/MemberProfileResponse.java
> +        .followee(getFollowee(member))
제 생각에는
```java
List<Member> getFollower(){
 this.getFollower().stream().map(Friend::getFollowee).toList();
}
```

요런 느낌으로 멤버에 메서드를 만들면 getFollower(), getFollowee() 둘 다 List<Member>를 반환하게 되므로 공통 Response로 묶을 수 있지 않을까 합니다!

2023-08-17 07:19 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/member/dto/response/memberProfile/MemberFolloweeResponse.java
> +
followee를 찾는 코드는 링크 주신 팔로우 테스트 코드보고 해결하고 Dto 통합도 성공했습니다!! 감사합니다..!!

follower를 찾는 경우에는 Member 엔티티의 메서드 가지고 해결하기 어렵다고 생각했습니다..! member.getFollower()를 하면 this로 들어간 제가 계속 follower로 들어가더라고요! 그래서 레포지토리에서 저를 followee한 Friend를 찾고 Friend::getFollowee로 Member를 찾아서 Dto로 넘겨서 Dto 통합을 완료했습니다!

2023-08-17 07:20 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/member/dto/response/memberProfile/MemberFolloweeResponse.java
> +public class MemberFolloweeResponse {
위에서 말씀해주신 내용으로 수정 완료했습니다 감사합니다~!!

2023-08-17 08:31 UTC, shkisme approved these changes
수고하셨습니다~!! 팔로잉, 팔로워까지 조회하는 게 쉽지 않았던 것 같은데 잘 해주신 것 같아요 ㅎㅎ 👍

2023-08-17 08:31 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/member/dto/response/memberProfile/MemberFriendResponse.java
> +package com.keeper.homepage.domain.member.dto.response.memberProfile;
혹시 패키지 이름 `memberProfile` -> `profile`로 변경해주실 수 있나요!?
패키지 네이밍으로 `camelcase`를 사용하지 않고 있어서요~

2023-08-17 08:31 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/member/api/MemberControllerTest.java
> +              )));
adoc 파일로 api 문서도 작성해주시면 좋을 것 같습니다~!

2023-08-17 08:31 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/member/entity/Member.java
> +        .collect(toList());
```suggestion
        .toList();
```
어떨까욥?

2023-08-17 08:31 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/member/dto/response/memberProfile/MemberProfileResponse.java
> +  }
`getFollower`와 `getFollowee`가 둘 다 `Member`를 인자로 받으면 좋겠네욥 ㅎㅎ
그럼 `of` 메서드에서 `List<Friend> friends`를 받지 않아도 될 것 같아요.
물론 지금 로직도 문제가 없는 것 같긴 합니다~! 😁

2023-08-18 12:13 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/member/entity/Member.java
> +        .collect(toList());
수정했습니다!! 감사합니당

2023-08-18 14:03 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/member/dto/response/profile/MemberProfileResponse.java
> +  }
```suggestion
        .follower(getFollower(member))
        .followee(getFollowee(member))
        .build();
  }

  private static List<MemberFriendResponse> getFollower(Member member) {
    return member.getFollower().stream()
        .map(Friend::getFollower)
        .map(MemberFriendResponse::from)
        .toList();
  }

  private static List<MemberFriendResponse> getFollowee(Member member) {
    return member.getFollowee().stream()
        .map(Friend::getFollowee)
        .map(MemberFriendResponse::from)
        .toList();
    }
  }
```

저는 요런 느낌을..! 생각하긴 했슴니다!!

2023-08-18 14:26 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/member/dto/response/profile/MemberProfileResponse.java
> +  }
public void follow(Member other) {
    follower.add(Friend.builder()
        .follower(this)
        .followee(other)
        .build());
  }
  위처럼 follower에 this가 들어가서 제 자신을 follower에 넣습니다..ㅠㅠ

2023-08-18 17:56 UTC, shkisme reviewed
죄송합니다...ㅇ 저도 이 부분 헷갈려서 인지 제대로 이해를 못하고 리뷰를 드린 것 같네요.. (어렵네요 😵‍💫
코멘트 확인 부탁드립니다!!!

2023-08-18 17:56 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/member/application/MemberService.java
> +    return MemberProfileResponse.of(findMember, findAllFollowers);
```suggestion
    Set<Friend> friends = findMember.getFollower();
    List<Member> follower = friends.stream().map(Friend::getFollower).toList();
    List<Member> followee = friends.stream().map(Friend::getFollowee).toList();

    return MemberProfileResponse.of(findMember, follower, followee);
```

이렇게 팔로워와 팔로잉 멤버 리스트를 뽑아서 DTO로 전달하는 건 어떨까요..?

예전에 `Friends` 엔티티 만들때 저도 많이 헷갈려서 고생하다가 아래처럼 `follower`와 매핑된 `friends` set 필드 하나만 두었었는데 ([레파지토리 테스트 코드](https://github.com/KEEPER31337/Homepage-Back-R2/blob/develop/src/test/java/com/keeper/homepage/domain/member/dao/friend/FriendRepositoryTest.java))
```java
@OneToMany(mappedBy = "follower", cascade = ALL, orphanRemoval = true)
private final Set<Friend> friends = new HashSet<>();
```

고스란히 까먹고 회원 팔로우, 언팔로우 기능 만들 때 이름도 다시 헷갈리게 바꾸고 (`follower`로) ... `follower`도 끼워넣었네요...

2023-08-18 18:24 UTC, shkisme reviewed
헷갈리네요 😵‍💫 커멘트 확인 부탁드립니다 !

2023-08-18 18:24 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/member/application/MemberService.java
> +    return MemberProfileResponse.of(findMember, findAllFollowers);
```suggestion
    Set<Friend> follower = findMember.getFollower();
    Set<Friend> followee = findMember.getFollowee();

    return MemberProfileResponse.of(findMember, follower, followee);
```

이렇게 팔로워와 팔로잉을 조회하고, `of` 메서드로 넘긴 뒤

2023-08-18 18:24 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/member/dto/response/profile/MemberProfileResponse.java
> +        .followee(getFollowee(member))
```java
 .follower(follower.stream().map(Friend::getFollowee).map(MemberFriendResponse::from).toList())
 .followee(followee.stream().map(Friend::getFollower).map(MemberFriendResponse::from).toList())
```

이렇게 매핑이 가능할 것 같은데 follower 컬렉션에서 getFollowee를 하는 부분이 헷갈려서 헤맸네요..! 멤버를 팔로우하는 정보를 가진 Friend 엔티티에서는 followee를 꺼내와야 상대방이 조회되네요..(어질)

2023-08-19 02:39 UTC, gusah009 requested changes
@shkisme 님이 suggestion 주신대로 하면 될 것 같은데, 한 번 시도해보고 다시 request 주세용~~ ( + 테스트 코드 커멘트도 확인 부탁드립니당)

2023-08-19 02:39 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/member/api/MemberControllerTest.java
> +      memberService.follow(memberTestHelper.builder().realName(RealName.from("사사")).build(), member.getId());
`follow`를 이렇게 한 김에 `.andExpect()`로 `follower`, `followee`가 잘 오는지도 테스트 해보면 좋을 것 같네요~ 아니면 아예 `MemberServiceTest`로 빼서 테스트해봐도 좋을 것 같구용~~

2023-08-19 08:32 UTC, 02ggang9 commented on src/test/java/com/keeper/homepage/domain/member/api/MemberControllerTest.java
> +      memberService.follow(memberTestHelper.builder().realName(RealName.from("사사")).build(), member.getId());
위의 코드 수정하고 바로 해보도록 하겠습니닷!! 감사합니다~~!!

2023-08-20 04:07 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/member/dto/response/profile/MemberProfileResponse.java
> +        .followee(getFollowee(member))
em.flush()랑 em.clear() 이젠 절대 안까먹을거 같네요.. OTL
정말 감사드립니당 속이 뻥 뚤리네요 👍👍

2023-08-20 05:09 UTC, 02ggang9 commented on src/test/java/com/keeper/homepage/domain/member/api/MemberControllerTest.java
> +      memberService.follow(memberTestHelper.builder().realName(RealName.from("사사")).build(), member.getId());
위 코드 해결하고 andExpect()로 테스트 해봤습니다~~ 감사합니닷!!

2023-08-20 07:50 UTC, gusah009 approved these changes
크으으..👍 어려운 부분이었을텐데 수고 많으셨습니다~~ 👍👍👍

2023-08-20 07:50 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/member/api/MemberController.java
> +    );
수정이 안된것같아용

2023-08-20 07:50 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/member/dto/response/profile/MemberProfileResponse.java
> +  }
아마 `N+1`문제가 발생할 것 같은데, 지금 키퍼 홈페이지 전반에 이 문제가 발생하는 API가 꽤 많을걸로 예상돼요 ㅎㅎ...

나중에 한 번 각잡고 고쳐보는것도 좋을 것 같습니당

2023-08-20 07:50 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/member/api/MemberControllerTest.java
> +          .andExpect(jsonPath("$.followee[0].name").value("일일"))
👍👍👍

2023-08-20 07:50 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/member/dao/friend/FriendRepository.java
> +  List<Friend> findAllByFollowee(Member member);
이건 안쓰이는것 같은데, 안쓰이면 없애시죵~

2023-08-20 07:50 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/member/api/MemberApiTestHelper.java
> +        fieldWithPath("followee[].thumbnailPath").description("팔로우 하는 사람의 썸네일 경로"),
`내가` 팔로우 하는 사람, `나를` 팔로우 하는 사람으로 설명을 바꾸는건 어떠신가요?

2023-08-20 09:48 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/member/dto/response/profile/MemberProfileResponse.java
> +  }
맞습니당... 계속 고민은 하고 있는데 fetch join, @EntityGraph, Batch Size 등등 어떤 방법을 써서 해결할 지에 대한 의논이 필요할 것 같네용.. 각각의 단점이 있는 것 같아서.. [hibernate.default_batch_fetch_size](https://github.com/KEEPER31337/Homepage-Back-R2/issues/113) 설정 적용도 해야지 했는데 기능 구현하느라 미뤄지고 있네요 🙃 (기능이 넘 많아효~~~!)

2023-08-20 09:49 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/member/dto/response/profile/MemberProfileResponse.java
> +  }
https://github.com/KEEPER31337/Homepage-Back-R2/issues/314 까먹기 전에 이슈 발행 해두었는데 좋은 의견 있다면 남겨두는 것도 좋을 것 같습니당~~!

2023-08-20 12:09 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/member/dto/response/profile/MemberProfileResponse.java
> +  }
그전까지 공부해오도록 하겠습니다!!!

2023-08-20 12:11 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/member/dao/friend/FriendRepository.java
> +  List<Friend> findAllByFollowee(Member member);
삭제했습니닷!! 감사합니당~~

2023-08-20 12:11 UTC, 02ggang9 commented on src/test/java/com/keeper/homepage/domain/member/api/MemberApiTestHelper.java
> +        fieldWithPath("followee[].thumbnailPath").description("팔로우 하는 사람의 썸네일 경로"),
많이 헷갈렸었는데 ㅎㅎ 수정했습니다~~!!

2023-08-20 13:51 UTC, merged