Feature/선거 후보자 등록 삭제 기능 구현
KEEPER31337/Homepage-Back-R2 pull request #316
Opened 2023-08-21 09:55 UTC by JJimini

## 🔥 Related Issue

> close: #305

## 📝 Description

> 선거 후보자 등록 및 삭제 기능을 구현했습니다.
> 선거 후보자 다중 등록 기능을 구현했습니다.

## ⭐️ Review Request

> 이 이슈 merge 되면 나머지 이슈 2개는 한 번에 하겠습니당~

2023-08-21 12:27 UTC, gusah009 requested changes
수고하셨습니다~ 커멘트 확인 부탁드려요!

2023-08-21 12:27 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/election/application/AdminElectionService.java
> +    }
위의 `registerCandidate`를 이용해서 아래처럼 재사용 할 수 있을 것 같네요~

그런데 1명 등록과 여러명 등록 API가 두 개 필요한 이유가 있을까요? 여러명 API로 1명만 등록해도 될 것 같아서요

```suggestion
    for (Long candidateId : candidateIds) {
      registerCandidate(description, memberJobId, electionId, candidateId);
    }
```

2023-08-21 12:27 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/election/application/AdminElectionService.java
> +  }
선거가 시작되거나 종료된 후에 후보자가 삭제되면 문제가 꽤 있을 것 같은데, 어떻게 생각하시나용

2023-08-21 12:27 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/election/application/convenience/ValidCandidateService.java
> +    if (!(memberJobId == 1 || memberJobId == 2 || memberJobId == 8)) {
상수대신 enum을 사용하면 더 가독성이 좋아질 것 같아요~

`!`로 부정문을 표현하기 보다 아래처럼 풀어쓰면 어떨까요? ([부정 조건문 지양하기](https://velog.io/@jangws/10.-%EB%B6%80%EC%A0%95-%EC%A1%B0%EA%B1%B4%EB%AC%B8-%EC%A7%80%EC%96%91%ED%95%98%EA%B8%B0))

> 이 부분은 호불호가 많이 갈리는 부분이긴 합니다... ㅎㅎ

```java
memberJobId != 1 && memberJobId != 2 && memberJobId != 8
```

\+ 여기서 더 나아가서 등록 가능한 job들을 가지는 collection을 만들어서 `.contains` 로 확인하면 더 가독성이 좋아질 것 같습니다~!

2023-08-21 12:27 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/election/application/AdminElectionService.java
> +  private final MemberFindService memberFindService;
서비스에서 서비스를 사용할 땐 반드시 순환 참조가 되지 않도록 해야합니다.

지금 문제가 되진 않지만 인지하고 있는게 좋을 것 같네요~

`MemberFindService` 구상 당시 의존성 그림입니다.

![image](https://github.com/KEEPER31337/Homepage-Back-R2/assets/26597702/18ee1166-f771-4107-95cb-57da43bf4e2f)

2023-08-21 12:27 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/election/application/convenience/ValidCandidateService.java
> +  private final MemberJobRepository memberJobRepository;
별 이유가 없다면 개행은 의미있게 사용하는게 좋습니다.

몇몇 부분에서 개행문제가 보이던데 다른 코드에도 적용 부탁드려요~

```suggestion
  private static final long VIRTUAL_ELECTION_CANDIDATE_ID = 1;
  
  private final ElectionCandidateRepository electionCandidateRepository;
  private final MemberJobRepository memberJobRepository;
```

2023-08-21 12:27 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/election/dto/request/ElectionCandidatesRegisterRequest.java
> +  private List<Long> candidateIds;
이 경우에 `List`의 각 원소들은 `nullable` 체크를 하지 않습니다.
그래서 NPE가 발생할 위험이 있는데, 그냥 알아두시면 좋을 것 같습니다 ㅎㅎ

(validation을 이용해서 각 요소에 nullable 체크를 해보는 것도 좋구요~)

2023-08-21 12:27 UTC, gusah009 commented on src/main/java/com/keeper/homepage/global/error/ErrorCode.java
> +  ELECTION_CANDIDATE_CANNOT_REGISTER("해당 멤버 ID는 후보자 등록 불가합니다.", HttpStatus.BAD_REQUEST),
멤버 ID가 아니라 memberJobId 인 것 같아요~

2023-08-21 12:27 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/election/ElectionCandidateTestHelper.java
> +          .memberJob(memberJob)
여기서 `memberJob`은 `ElectionCandidate`를 만들 때 반드시 들어가야 하는걸로 보이는데요, 코드에서 이걸 강제하려면 `ElectionCandidateTestHelper` 코드를 어떻게 바꾸면 될까요? ㅎㅎ 한 번 고민해보셔도 좋을 것 같습니다.

> 너무 어려우시면 그냥 `memberJob`도 `null` 체크를 해서 기본적으로 회장 권한으로 후보자를 생성하게끔 하는 것도 좋을 것 같아요~

2023-08-21 12:27 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/election/application/AdminElectionServiceTest.java
> +            .build();
해당 `electionCandidate`는 불필요한 것 같아요.

2023-08-21 12:27 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/election/application/AdminElectionServiceTest.java
> +      List<Long> candidateIds = new ArrayList<>();
nit: mutable한 list를 만들기보다 생성시에 바로 immutable한 list를 만들 수 있으면 더 좋습니다.

[불변 객체를 사용해야 하는 이유](https://mangkyu.tistory.com/131)

2023-08-21 12:27 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/election/application/AdminElectionServiceTest.java
> +      long improperMemberJobId = 3;
3 대신 enum을 사용해주시면 더 좋을 것 같습니다~

2023-08-21 12:27 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/election/application/AdminElectionServiceTest.java
> +              electionId, candidateId));
exceptionMsg도 함께 검사해주면 더 좋을 것 같아요

2023-08-21 12:27 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/election/application/AdminElectionServiceTest.java
> +      electionCandidateRepository.deleteAll();
이것도 위 커멘트에 이어서 불필요한 코드인 것 같습니다

2023-08-21 12:27 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/election/application/AdminElectionServiceTest.java
> +      long notExistCandidateId = 10;
`notExistCandidateId` 변수명 👍👍

2023-08-22 05:41 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/election/application/AdminElectionService.java
> +    }
저도 여러명 api로 1명만 등록하는 것도 괜찮다고 생각합니다! 오늘 회의 때 말씀드리고 수정하겠습니다~!

2023-08-22 05:42 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/election/application/AdminElectionService.java
> +  }
네 그렇네용 이 부분도 선거 시작 전에만 삭제할 수 있도록 수정하겠습니다!

2023-08-22 12:24 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/election/application/AdminElectionService.java
> +    }
이 부분은 지금 만들어둔 1명 등록 api는 그냥 남겨두고, 다음부터 1명 등록 api는 만들지 않는 것으로 이야기했습니다!

2023-08-22 12:27 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/election/application/AdminElectionService.java
> +  }
지금 이 부분은 선거 시작 전에만 삭제할 수 있도록 할 수 있는 방법이 없습니다.. 기획 상 `선거시작`,  `선거중`, `선거완료` 를 구분하지 않는다고 합니다

2023-08-22 12:28 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/election/application/convenience/ValidCandidateService.java
> +  private final MemberJobRepository memberJobRepository;
어려운 개행...

2023-08-22 12:37 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/election/application/convenience/ValidCandidateService.java
> +  private final MemberJobRepository memberJobRepository;
개행.. 역시 어렵습니다..ㅎ

2023-08-22 12:38 UTC, JJimini commented on src/test/java/com/keeper/homepage/domain/election/ElectionCandidateTestHelper.java
> +          .memberJob(memberJob)
@gusah009 이 부분도 수정해보았는데 의도하신 방향이 맞는지 궁금합니다!

2023-08-22 14:01 UTC, gusah009 approved these changes
후보자 삭제시 어떻게 할 지만 잘 정하면 될 것 같네요~ 그 외엔 자잘한 커멘트들이라 approve 하겠습니다!

수고 많으셨습니다~ 👍👏👍👏

2023-08-22 14:01 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/election/application/AdminElectionServiceTest.java
> +      electionCandidateRepository.deleteAll();
한 번 모두 지워주는 이유는 뭘까요? 최종적으로 6개가 나오는 것 보다 5개가 나오는게 직관적이어서?

2023-08-22 14:03 UTC, gusah009 approved these changes

2023-08-22 14:03 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/election/application/AdminElectionServiceTest.java
> +      assertEquals("해당 직위는 후보자 등록 불가합니다.", exception.getMessage());
```suggestion
      assertThrows(BusinessException.class,
          () -> adminElectionService.registerCandidate(electionCandidate.getDescription(), memberJob.getId(),
              electionId, candidateId),
              "해당 직위는 후보자 등록 불가합니다.");
```

2023-08-22 14:06 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/election/api/AdminElectionController.java
> +  }
넵 이 부분은 지금 만들어둔 1명 등록 api는 그냥 남겨두고, 다음부터 단일 등록 api는 만들지 않는 것으로 이야기했습니다!

2023-08-22 14:08 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/election/dto/request/ElectionCandidatesRegisterRequest.java
> +  private List<@NotNull Long> candidateIds;
동작 한다고 알고 있는데 지금 테스트 중입니다~! 나중에 테스트 코드 추가해두겠습니당

2023-08-22 14:11 UTC, JJimini commented on src/test/java/com/keeper/homepage/domain/election/application/AdminElectionServiceTest.java
> +      assertEquals("해당 직위는 후보자 등록 불가합니다.", exception.getMessage());
아하 합쳐지는군요!!👍👍

2023-08-23 06:44 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/election/application/convenience/ValidCandidateService.java
> +  private static final List<Long> VALID_MEMBER_JOB_IDS = Arrays.asList(1L, 2L, 8L);
```java
  public enum MemberJobId {
    ROLE_회장(1),
    ROLE_부회장(2),
    ROLE_총무(8);

    private final long id;

    MemberJobId(long id) {
      this.id = id;
    }

  }
  ```
  이런 식으로 `Enum` 추가하는 방식을 말씀하시는 건가요 아니면 아래 코드와 같이 상수만 바꾸는 방식을 말씀하시는 건가용??
  
  ```java
  private static final List<Long> VALID_MEMBER_JOB_IDS = Arrays.asList(ROLE_회장.getId(), ROLE_부회장.getId(), ROLE_총무.getId());
  ```
  일단 수정은 첫번째 방법으로 하긴 했습니다!

2023-08-23 09:23 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/election/application/AdminElectionService.java
> +  }
그럼 선거가 비공개 상태일 때만 삭제가 가능하도록 하는 것은 어떻습니까? @shkisme 
그렇게 되면 선거중일때는 투표가 공개 상태일테니 후보자 삭제가 불가능할 것 같습니다!

2023-08-23 10:52 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/election/application/AdminElectionService.java
> +  }
좋습니다! 비공개 상태일 때만 삭제가 가능하도록 구현하면 될 것 같습니다~! 👍

2023-08-23 11:18 UTC, shkisme approved these changes
수고하셨습니다~!! 굿굿굿 👍👍

2023-08-23 11:18 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/election/application/convenience/ValidCandidateService.java
> +        .anyMatch(jobId -> jobId.id == memberJobId);
```suggestion
    return Arrays.stream(CandidateJob.values())
        .anyMatch(job -> job.id == memberJobId);
```

어떨까요? 그리고 `enum` 이름은 후보자 직위인 `CandidateJob`은 어떤가용?

2023-08-23 11:18 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/election/application/AdminElectionServiceTest.java
> +          electionCandidate.getId()), "비공개 상태 선거에서만 후보자 삭제가 가능합니다.");
```suggestion
          electionCandidate.getId()), ELECTION_CANDIDATE_CANNOT_DELETE.getMessage());
```

이렇게 할 수 있습니다! 이렇게 하면 메세지가 변경되어도 테스트를 수정하지 않아도 될 것 같아요~!

2023-08-23 11:18 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/election/application/AdminElectionServiceTest.java
> +             private List<Long> candidateIds;              => 실패
오! 혹시 이 부분 추가 설명 부탁드려도 될까요? 🙂 지금 적용되어 있는 1번이 null 값을 잘 걸러준다는 건가용?
그리고 서비스 로직이 아닌 요청받는 값에 대한 테스트라면 컨트롤러 테스트에서 진행하는 게 어떤가 합니당!

2023-08-23 11:38 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/election/application/convenience/ValidCandidateService.java
> +        .anyMatch(jobId -> jobId.id == memberJobId);
이 부분이 깔끔하지 못하다고 생각해서 저도 고민중이었는데, `Enum`을 따로 만들어두는게 괜찮을 지, 아니면 원래 List 방식에서 상수로 받는 것이 아닌` ROLE_회장.getId()` 형태로 받는게 좋을지 고민입니당..

2023-08-23 11:43 UTC, JJimini commented on src/main/java/com/keeper/homepage/domain/election/application/convenience/ValidCandidateService.java
> +        .anyMatch(jobId -> jobId.id == memberJobId);
이 부분 수정 완료했습니다!
```java
  private static final List<Long> VALID_MEMBER_JOB_IDS = Arrays.asList(ROLE_회장.getId(), ROLE_부회장.getId(),
      ROLE_총무.getId());
```
이렇게 받는 게 더 깔끔해보여서 수정했습니다!

2023-08-23 11:44 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/election/application/convenience/ValidCandidateService.java
> +        .anyMatch(jobId -> jobId.id == memberJobId);
아니면 기존에 있는 `MemberJob`에 메서드를 추가하는 것도 깔끔한 방법이 될 것 같아용!

```java
public boolean isCandidate() {
    return this.type == ROLE_회장 || this.type == ROLE_부회장 || this.type == ROLE_총무;
}
```

2023-08-23 12:51 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/election/application/AdminElectionServiceTest.java
> +             private List<Long> candidateIds;              => 실패
오 그렇군용~! 저도 확인해보니 정상적으로 동작하는 것 같아서 다른 다중 추가 파트들에도 적용해야겠네요 👍👍👍 최고
리스트에 `null`을 담아서 보낼 경우 서비스 코드로 넘어가지 않고, 컨트롤러 단에서 예외처리를 하는 것이기 때문에 컨트롤러에 해당 테스트를 추가해두면 좋은 것 같긴 합니당 ㅎㅎ 😄

<img width="902" alt="image" src="https://github.com/KEEPER31337/Homepage-Back-R2/assets/92802207/cab60cfe-3956-43e9-ab82-cf17d80ee921">

2023-08-24 07:50 UTC, merged