👀Feature/회원 탈퇴 기능
KEEPER31337/Homepage-Back-R2 pull request #350
Opened 2023-09-05 06:24 UTC by 02ggang9

## 🔥 Related Issue

## 📝 Description

회원 탈퇴 기능을 만들었습니다.

## ⭐️ Review Request

초반 커밋을 보시면 회원 아이디, 비밀번호, 이메일 등등 전부 다 탈퇴, 삭제 등으로 마킹을 했었는데 의견을 나눈 결과 is_delete를 업데이트하고 회원 이름만 탈퇴회원으로 마킹하도록 했습니다..!! (게시글에 탈퇴회원으로 표기되게끔) 다른 분들의 의견도 궁금합니다~ 어떻게 해야 할까요 ?.?
👀

2023-09-06 12:33 UTC, gusah009 requested changes
수고 많으셨습니다~ 척척 개발해내시네용 👍👍

2023-09-06 12:33 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/member/entity/Member.java
> +  }
`is`보단 `has`가 어울릴 것 같고, `bookBorrowInfo`가 로그 성질을 가지고 있어서 반납을 완료했더라도 "반납완료"로 `bookBorrowInfos`를 가지고 있습니다. 그래서 아래 suggestion 처럼 해주어야 실제로 빌리고 있는 책들이 있는지 확인할 수 있습니다.

```suggestion
  public boolean hasAnyBorrowBooks() {
    return this.bookBorrowInfos.stream()
        .anyMatch(BookBorrowInfo::isInBorrowing);
  }
```

2023-09-06 12:33 UTC, gusah009 commented on src/main/java/com/keeper/homepage/global/error/ErrorCode.java
> +  MEMBER_BOOK_NOT_EMPTY("아직 대여 중인 책이 있어 탈퇴가 불가능합니다.", HttpStatus.BAD_REQUEST),
👍👍

2023-09-06 12:33 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/member/application/MemberServiceTest.java
> +    public void 대출_중인_도서가_있을_경우_예외를_던진다() {
👍👍👍

2023-09-07 14:50 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/member/entity/embedded/Profile.java
> +  }
아..!! @Where 어노테이션을 붙여야겠다고 생각했는데 못 붙였네요!!

원래는 login_id, password, name 등등 "(삭제)"로 마킹하기로 했는데 구글링을 해보니 is_delete만 업데이트 하고 다른 부분은 마킹을 하지 않더라고요! 그래서 is_delete만 업데이트하는 게 어떤지 의견을 나눠었는데 게시글 작성자 같은 부분은 탈퇴회원이라고 명시해주는 것이 좋을 거 같아서 이렇게 결정했습니다!

2023-09-07 14:53 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/member/entity/Member.java
> +  }
수정했습니다~! suggestion 감사합니다!!

2023-09-09 02:13 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/member/entity/embedded/Profile.java
> +  }
아하 그럼 로그인시에 `is_delete`가 true면 회원이 있어도 로그인이 안되는 로직이 있긴 해야겠네요...

리뉴얼1때도 회원이 탈퇴하면 row를 날릴지 마킹만 할 지 고민하다가 row를 날리기로 했던 이유가 개인정보때문이었는데, 그것도 한 번 알아보시면 좋을 것 같아요~

2023-09-09 02:19 UTC, gusah009 approved these changes
`@Where` 어노테이션을 사용해주셨군요..! 탈퇴를 마킹하기 너무 좋은 어노테이션이긴 하지만 JPQL을 직접 사용하면 무시되는 특징이 있는 것 같더라구요. 저희 프로젝트에서 JPQL을 많이 쓰기도 하고, 혹여나 JPQL을 사용해서 `is_deleted`가 무시되면 탈퇴한 회원의 정보가 나올까 걱정되긴 하네요.. 그런데 더 나은 방법이 생각나진 않아서 approve 해두겠습니다 ㅎㅎ..

2023-09-09 03:07 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/member/entity/embedded/Profile.java
> +  }
개인정보랑 아래에 말씀해주신 jpql 사용하면 무시되는 것도 한번 찾아보고 고민해보도록 하겠습니다..!! 감사합니다~!

2023-09-09 03:23 UTC, shkisme approved these changes
수고하셨습니다~!!
저도 고민이 많이 되었던 기능이였는데 너무 잘 구현해주신 것 같습니다 👍

2023-09-09 03:23 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/member/application/MemberServiceTest.java
> +      member.borrow(book, getBookBorrowStatusBy(대출대기));
`hasAnyBorrowBooks()`에서는 `대출중`, `반납대기` 상태의 도서 대여 정보가 있는지 확인하고 있는데 테스트 코드에서는 `대출대기` 상태의 도서를 갖고있을 때 탈퇴가 안되는 지 체크하고 있는 것 같아요!

2023-09-09 03:23 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/member/application/MemberServiceTest.java
> +    public void 회원_탈퇴_시_유저_이름은_회원탈퇴로_마킹되어야_한다() {
Nit: 사소하지만 테스트 이름도 실제 결과와 동일하게 맞춰주면 좋을 것 같아용! `'탈퇴회원'으로 마킹되어야 한다` 어떨까요?

2023-09-09 03:37 UTC, 02ggang9 commented on src/main/java/com/keeper/homepage/domain/member/entity/embedded/Profile.java
> +  }
개인정보에 관한 말씀이 아래에 있는 내용이 맞을까요?? PDF 기준으로 91이고 서류 페이지로는 85쪽 입니다..!!
https://www.gne.go.kr/upload_data/board_data/BBS_0000852/163895639273171.pdf

2023-09-09 03:39 UTC, 02ggang9 commented on src/docs/asciidoc/member/member.adoc
> +
좋은 거 같습니다..!! 수정하도록 하겠습니다~ 감사합니다..!!

2023-09-09 03:50 UTC, 02ggang9 commented on src/test/java/com/keeper/homepage/domain/member/application/MemberServiceTest.java
> +    public void 회원_탈퇴_시_유저_이름은_회원탈퇴로_마킹되어야_한다() {
엇..!! 그렇네요!! 감사합니다~!

2023-09-10 08:50 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/member/entity/embedded/Profile.java
> +  }
@02ggang9 와우... 사실 저흰 회원이 탈퇴하면 row를 날리자고 결정을 했어서 개인정보를 언제 파기하는지에 대해선 따로 못봤었는데 이런 문서가 있었군요~ 👍👍

문서에서 나온대로 진행하면 좋을 것 같은데, 제가 이해하기론 모든 컬럼을 다 덮어써버려야 할 것 같긴 하네요

2023-09-16 15:36 UTC, 02ggang9 commented on src/test/java/com/keeper/homepage/domain/member/application/MemberServiceTest.java
> +      member.borrow(book, getBookBorrowStatusBy(대출대기));
엇!! 그렇네요~ 수정하도록 하겠습니다! 감사합니다..!!

2023-09-17 13:13 UTC, gusah009 approved these changes

2023-09-18 07:45 UTC, shkisme approved these changes
수고하셨습니다~!! 👍

2023-09-18 13:03 UTC, merged