Feature/도서 프론트 요청사항
KEEPER31337/Homepage-Back-R2 pull request #351
Opened 2023-09-07 07:18 UTC by shkisme

## 🔥 Related Issue

> close: #없음

## 📝 Description

- 도서 목록 조회
  - 대출 상태가 대출 대기, 대출 중, 반납 대기 인 경우 도서 목록 응답의 canBorrow를 false로 반환하게
- 도서 대여 목록 조회
  - `대출 대기` 상태의 대여 정보도 불러오도록 수정
  - 대출 상태 응답으로 추가
  - 도서 썸네일 주소 응답으로 추가

## ⭐️ Review Request

6cfdd7e879dbc83df01887626b57d6b908c04944 이 커밋만 봐주셔도 될 것 같습니다!

2023-09-07 14:12 UTC, JJimini approved these changes
수고하셨습니당👍

2023-09-07 14:14 UTC, gusah009 requested changes
대출할 때 대출이 가능한지 여부를 따지는 `canBorrow()` 메서드가 도서 목록 조회에서만 유효한 것 같습니다. 실제 대출을 할 때에는 `canBorrow()` 메서드가 쓰이질 않아서 목록상에는 대출이 가능하다고 되어 있는데 실제론 대출이 되지 않거나 하는 식으로 문제가 생길 수도 있을 것 같네요.

2023-09-07 14:14 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/library/application/BookService.java
> +    }
> bookBorrowInfo가 로그 성질을 가지고 있어서 반납을 완료했더라도 "반납완료"로 bookBorrowInfos를 가지고 있습니다. 그래서 아래 suggestion 처럼 해주어야 실제로 빌리고 있는 책들이 있는지 확인할 수 있습니다.

참고: https://github.com/KEEPER31337/Homepage-Back-R2/pull/350#discussion_r1317209388

2023-09-07 14:25 UTC, 02ggang9 commented on src/test/java/com/keeper/homepage/domain/library/api/BookApiTestHelper.java
>          fieldWithPath("borrowInfoId").description("빌린 전보 ID"),
오타가 있는 거 같습니다~

2023-09-08 08:30 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/library/api/BookApiTestHelper.java
>          fieldWithPath("borrowInfoId").description("빌린 전보 ID"),
앗 그렇네요 발견 감사합니다!! 👍

2023-09-08 08:36 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/library/application/BookService.java
> +    }
코드를 위 처럼 작성한 이유는 아예 책을 빌린 정보가 없을 경우에 대한 처리를 하려고 해서 그렇습니다!

실제로 빌리고 있는 책들이 있는지 확인은 BookBorrowInfo.isCanBorrow()로 했구요!

> 대출할 때 대출이 가능한지 여부를 따지는 canBorrow() 메서드가 도서 목록 조회에서만 유효한 것 같습니다. 실제 대출을 할 때에는 canBorrow() 메서드가 쓰이질 않아서 목록상에는 대출이 가능하다고 되어 있는데 실제론 대출이 되지 않거나 하는 식으로 문제가 생길 수도 있을 것 같네요.

도서 대출 신청에서 canBorrow()를 사용하는 게 좋을 것 같네요!!

2023-09-09 02:34 UTC, gusah009 approved these changes
수고하셨습니다~~ 👍👍👍

2023-09-09 02:45 UTC, merged