feat: Friend Entity, Repository 생성 #38
KEEPER31337/Homepage-Back-R2 pull request #42
Opened 2023-01-26 04:00 UTC by shkisme

## 🔥 Related Issue

close: #38 

## 📝 Description

Friend Entity, Repository 생성하였습니다!

## ⭐️ Review

후딱 만들어봤습니다 😀

2023-01-26 05:24 UTC, gusah009 requested changes

2023-01-26 05:24 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/member/entity/Member.java
> +
`List`로 만들면 중복된 `follow`가 들어갈 수도 있지 않을까요?

2023-01-26 10:50 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/member/entity/Member.java
> +
아이고 그렇네요!! Set으로 수정했습니다!

2023-01-26 12:22 UTC, gusah009 requested changes
`Set`으로 했을 때 정말 중복 데이터가 들어가지 않을까요?

테스트코드도 작성해 보시는 걸 추천드립니다!

2023-01-26 12:30 UTC, shkisme commented
> `Set`으로 했을 때 정말 중복 데이터가 들어가지 않을까요?
> 
> 테스트코드도 작성해 보시는 걸 추천드립니다!

으악 딱걸렸네요...ㅋㅋㅋㅋ 테스트 작성해보겠습니답!!!

2023-01-27 00:16 UTC, shkisme commented
테스트 짜기 전에 여럿 실수를 했었네요.. 허허 저는 감자입니다 🥔

2023-01-27 00:53 UTC, gusah009 requested changes
커멘트 확인 부탁드립니다!

2023-01-27 00:53 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/member/dao/friend/FriendRepositoryTest.java
> +    }
`Friend` 엔티티의 `@equalsAndHashCode` 부분을 다시 한 번 확인해 보시길 바랍니다.

아래 테스트 코드는 실패합니다.

```java
@Test
@DisplayName("회원의 follower 정보에는 중복된 값이 들어가면 안된다.")
void should_nothingHappens_when_duplicateFollower() {
  Member findMember = memberRepository.findById(member1.getId()).orElseThrow();

  findMember.addFollower(member2);
  findMember.addFollower(member2);
  findMember.addFollower(member2);
  em.flush();
  em.clear();
  findMember = memberRepository.findById(member1.getId()).orElseThrow();
  findMember.addFollower(member2);

  assertThat(friendRepository.findAll()).hasSize(1); // 실패합니다
}
```

2023-01-27 00:53 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/member/entity/Member.java
> +  }
`addFollower()`, `addFollowee()` 보다 `follow()`, `unfollow()`를 만드는 건 어떤가요?

```java
// 내가 다른 사람을 팔로우 할 때
other.addFollower(member);
member.addFollowee(other);
```

개인적으로 위 코드보다 아래 코드가 더 이해하기 쉬울 것 같은데, 어떻게 생각하시는 지 궁금합니다!

```java
// 내가 다른 사람을 팔로우 할 때
member.follow(other);
```

2023-01-27 02:58 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/member/entity/Member.java
> +  }
훨씬 직관적이네요! 좋은 의견 감사합니다!!

2023-01-27 03:35 UTC, woo-chang commented on src/main/java/com/keeper/homepage/domain/member/entity/friend/Friend.java
> +  }
사소하지만 `@EqualsAndHashCode`라는 어노테이션을 활용하면 코드를 줄일 수 있을 것 같습니다 ⛄️

2023-01-27 04:36 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/member/entity/friend/Friend.java
> +  }
그러네요! 감사합니다~!

2023-01-28 02:48 UTC, gusah009 approved these changes
👏👏👏 새벽까지 수고 많으셨어요~!

2023-01-28 13:08 UTC, woo-chang approved these changes
수고하셨습니다 ⛄️

2023-01-29 02:11 UTC, merged