Feature/seminar 관련 entity repository 생성
KEEPER31337/Homepage-Back-R2 pull request #74
Opened 2023-02-01 14:48 UTC by hyuunnn

## 🔥 Related Issue

close: #4

## 📝 Description

`Seminar`, `SeminarAttendance`, `SeminarAttendanceStatus`, `SeminarAttendanceExcuse` Entity, Repository 생성 및 테스트 코드 작성하였습니다.

## ⭐️ Review

2-3일 정도 계속 보니까 제가 맞게 했는지도 잘 모르겠네요 ㅋㅋ.. 리뷰 보면서 고쳐나가겠습니다..!
지금까지 개발하면서 테스트 코드 작성을 해본 적이 없는데 생각보다 오래 걸리네요. (지금까지 print에 의존했습니다...)
유의미한 테스트 코드 작성과 관련된 공부도 해야겠네요...!

* `SeminarAttendanceRepositoryTest` 코드 작성 중에 의문이 생겼는데, 테스트 코드에서 `save`를 했을 때 `em.flush()`, `em.clear()`를 해주지 않으면 에러가 뜨던데 생명 주기가 끝나지 않아서 그런걸까요..? `delete`할 때는 `em.flush()`, `em.clear()` 없이 바로 반영이 되었습니다..!
* `SeminarAttendanceRepositoryTest` 코드에서 영속성 컨텍스트를 비우고 `reFindAttendance`라는 새로운 변수에 데이터를 다시 `find`해서 사용하는데, 코드가 더러워진다는 느낌을 받아서 더 좋은 방법이 있는지 궁금합니다..! (생명 주기가 끊긴 상태라서 재사용하지 못합니다.)

2023-02-01 16:09 UTC, shkisme reviewed
정말 생각을 많이 하시면서 코드를 작성하신 게 느껴집니다!! 수고하셨어요! 👍
리뷰 확인 부탁드립니당

2023-02-01 16:09 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/clerk/seminar/dao/SeminarAttendanceRepositoryTest.java
> +    }
실제 저장은 setUp()에서 하고 있고, 요 테스트는 조회가 잘 되는지 테스트를 하는 것 같은데 혹시 어떻게 생각하시나요?

2023-02-01 16:37 UTC, shkisme commented
> 테스트 코드에서 save를 했을 때 em.flush(), em.clear()를 해주지 않으면 에러가 뜨던데

혹시 어떤 상황에서 어떤 에러가 떴나요? 저장이 반영되지 않는 문제가 생기나요?

2023-02-01 16:41 UTC, woo-chang reviewed
수고하셨습니다 👍👍

코드에서 고민의 흔적이 많이 느껴졌습니다! 저 또한 많이 생각할 수 있었습니다 :)

2023-02-01 16:41 UTC, woo-chang commented on src/main/java/com/keeper/homepage/domain/clerk/entity/seminar/Seminar.java
> +@DynamicUpdate
`@DynamicInsert`, `@DynamicUpdate` 어노테이션 사용하셨네요 👍👍

데이터가 존재하는 필드만으로 쿼리를 생성하지만, 동적으로 쿼리를 생성하기에 컬럼 개수가 적은 테이블에서는
오히려 성능 저하를 발생시킬 수도 있다고 합니다. 이 부분도 한번 고민할 수 있으면 좋을 것 같아요 ⛄️

2023-02-01 16:41 UTC, woo-chang commented on src/main/java/com/keeper/homepage/domain/clerk/entity/seminar/Seminar.java
> +  private LocalDateTime registerTime;
등록 시간과 같은 반복해서 사용되는 컬럼은 `BaseEntity`로 만들어서 상속해서 사용하면 중복되는 코드를 줄일 수 있습니다

@hyuunnn 님이 우선적으로 도입해보셔도 좋을 것 같아요 :)

2023-02-01 16:41 UTC, woo-chang commented on src/test/java/com/keeper/homepage/domain/clerk/seminar/SeminarTestHelper.java
> +          .openTime(sampleTime)
DB 대조표를 봤을 때는 **open_time**에는 `default` 값이 들어가네요

`@DynamicInsert`를 사용하신만큼 무조건적으로 값을 주지 않고, `null`을 넣었을 때 `default` 값이 잘 적용되는지 확인해보는 건 어떨까요 ?

2023-02-01 16:41 UTC, woo-chang commented on src/test/java/com/keeper/homepage/domain/clerk/seminar/dao/SeminarRepositoryTest.java
> +    em.clear();
`flush`, `clear`를 사용하면 캐시된 쿼리가 날라가고 영속성 컨텍스트가 비워지기에 확실한 테스트를 보장할 수 있겠네요 👍

**영한님** 말씀에 의하면 실무에서는 트랜잭션 종료 시 발생하는 커밋을 이용해 `flush`, `clear`를 실제로 사용하는 일이 없다고 합니다.
테스트 코드도 IntegrationTest에 붙은 `@Transactional`에 의해 관리되고 있기에, flush, clear 사용을 줄이도록 해보는 건 어떨까요? 이 부분도 정답은 없기에 한번 고민해보셨으면 좋겠습니다!

2023-02-01 16:41 UTC, woo-chang commented on src/main/java/com/keeper/homepage/domain/clerk/converter/SeminarAttendanceStatusTypeConverter.java
> +public class SeminarAttendanceStatusTypeConverter implements
`@Converter` 적용 좋습니다 👏🏻👏🏻

2023-02-01 16:41 UTC, woo-chang commented on src/main/java/com/keeper/homepage/domain/clerk/entity/seminar/SeminarAttendance.java
> +    indexes = @Index(name = "is_seminar_attendance_duplicated", columnList = "seminar_id, member_id", unique = true))
꼼꼼한 작성 좋습니다 👍👍

제가 알기로는 해당 설정은 해당 정보를 바탕으로 테이블을 생성해서 사용할 때 적용되는 것으로 알고 있습니다.
저희는 만들어진 테이블에 매핑해서 사용하고 있기에 작성한다고 해서 테이블에 인덱스가 적용되지 않을꺼에요 .. !

실제로 인덱스가 적용되어 있다면 코드를 통해 인덱스가 적용되어 있다고 알려줄 수 있기에 작성하는 건 좋다고 생각합니다 ⛄️

2023-02-01 16:41 UTC, woo-chang commented on src/main/java/com/keeper/homepage/domain/clerk/entity/seminar/SeminarAttendanceExcuse.java
> +  @MapsId
해결하신다고 수고하셨습니다 👏🏻👏🏻

https://developer-ping9.tistory.com/296

이 글을 읽어보시면 조금 더 도움되실꺼에요 :)

2023-02-01 16:48 UTC, hyuunnn commented
@shkisme 
`reFindAttendance.getSeminarAttendanceExcuse()`를 호출할 때 NPE가 터지네요 ㅎ..
![image](https://user-images.githubusercontent.com/15611739/216107491-159cf133-00d7-4a91-98e3-b74746f5dd57.png)

2023-02-01 16:51 UTC, hyuunnn commented on src/test/java/com/keeper/homepage/domain/clerk/seminar/dao/SeminarRepositoryTest.java
> +    em.clear();
https://github.com/KEEPER31337/Homepage-Back-R2/pull/74/commits/a715e52099ea417e47a16d08470e3fff3c04dd82 여기서 반영 되었습니다..! ㅎ

2023-02-01 16:52 UTC, hyuunnn commented on src/test/java/com/keeper/homepage/domain/clerk/seminar/SeminarTestHelper.java
> +          .openTime(sampleTime)
정말 좋은 의견이네요! 수정해보겠습니다 :)

2023-02-01 16:55 UTC, hyuunnn commented on src/main/java/com/keeper/homepage/domain/clerk/entity/seminar/Seminar.java
> +@DynamicUpdate
DB에서 current_time으로 넣어주는 테이블에는 넣어야한다고 들었던 것 같은데 아닌가보네요 ㅎㅎ.. 제대로 공부해보고 의문점 있으면 다시 질문 남기겠습니다 :)

2023-02-01 16:57 UTC, hyuunnn commented on src/main/java/com/keeper/homepage/domain/clerk/entity/seminar/Seminar.java
> +  private LocalDateTime registerTime;
<a href="http://www.yes24.com/Product/Goods/83849117">스프링 부트와 AWS로 혼자 구현하는 웹 서비스</a>에서 봤던 코드네요 ㅎㅎ <a href="https://github.com/hyuunnn/spring-aws-book/blob/master/src/main/java/com/spring/book/springboot/domain/BaseTimeEntity.java">BaseTimeEntity.java</a>

좋은 의견 감사합니다 :)

2023-02-01 17:02 UTC, woo-chang commented
> #### 질문
> * `SeminarAttendanceRepositoryTest` 코드 작성 중에 의문이 생겼는데, 테스트 코드에서 `save`를 했을 때 `em.flush()`, `em.clear()`를 해주지 않으면 에러가 뜨던데 생명 주기가 끝나지 않아서 그런걸까요..? `delete`할 때는 `em.flush()`, `em.clear()` 없이 바로 반영이 되었습니다..!
> * `SeminarAttendanceRepositoryTest` 코드에서 영속성 컨텍스트를 비우고 `reFindAttendance`라는 새로운 변수에 데이터를 다시 `find`해서 사용하는데, 코드가 더러워진다는 느낌을 받아서 더 좋은 방법이 있는지 궁금합니다..! (생명 주기가 끊긴 상태라서 재사용하지 못합니다.)

첫 번째 질문은 코드와 같이 예시를 들어주시면 조금 더 와닿을 것 같아요!

두 번째 질문은 연관관계로 데이터를 잘 가져오는지 확인하는 상황에서 발생하는 고민일 것 같아요. flush, clear를 사용한다면 다시 조회해야만 테스트가 가능할 것 같아요!
제가 생각한 방법으로는 영한님 강의에서 나오는 연관관계 편의 메서드를 활용해볼 수 있을 것 같아요

`SeminarAttendance`에서 `cascade.PERSIST`로 사유를 관리한다면, 아래와 같은 연관관계 메서드를 작성해볼 수 있습니다
```java
public void absent(String excuse) {
  SeminarAttendanceExcuse seminarAttendanceExcuse = SeminarAttendanceExcuse.builder()
    .seminarAttendance(this)
    .absenceExcuse(excuse)
    .build();
  this.seminarAttendanceExcuse = seminarAttendanceExcuse;
}
```
해당 코드를 사용하면 다시 `DB`에서 불러오지 않아도 사유가 연결되어 있기에 테스트하기에 조금 더 용이할 거라 생각합니다!
`DB`에서 불러오는게 가장 확실한 테스트이긴 한 것 같습니다 ㅎㅎ..

2023-02-01 17:25 UTC, hyuunnn commented
@woo-chang 테스트 코드를 작성하는 요령이 없다 보니 고민할게 많네요 ㅋㅋ..
시간날 때마다 다양한 책들 읽어보면서 지식을 넓혀야겠습니다 ㅠㅠ
<a href="https://jojoldu.tistory.com/226">향로</a>님이 추천하시는 <a href="http://www.yes24.com/Product/Goods/11361087">Effective Unit Testing</a>, <a href="http://www.yes24.com/Product/Goods/75189146">자바와 JUnit을 활용한 실용주의 단위 테스트</a>, <a href="http://www.yes24.com/Product/Goods/104084175">단위 테스트</a> 등등 봐야겠네요..

2023-02-01 22:49 UTC, gusah009 reviewed
수고 많으셨어요!! ㅎㅎ

2023-02-01 22:49 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/clerk/entity/seminar/Seminar.java
> +  private LocalDateTime registerTime;
아니면 아예 Entity상에서 `registerTime`과 `updateTime`을 빼버리는 것도 좋을 것 같습니다!

사실상 DB 테이블 기록용 컬럼이라서 비즈니스 로직에서 쓰일 일이 없다고 생각되시면 아예 삭제하셔도 될 것 같아요.

그러면 `@DynamicInsert`나 `@DynamicUpdate` 없이도 알아서 DB Default 값이 들어갈겁니다!

2023-02-01 22:49 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/clerk/entity/seminar/SeminarAttendance.java
> +    indexes = @Index(name = "is_seminar_attendance_duplicated", columnList = "seminar_id, member_id", unique = true))
인덱스 명시한건 너무 좋은 것 같아요!

2023-02-01 22:49 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/clerk/entity/seminar/SeminarAttendanceExcuse.java
> +  @MapsId
수고 많으셨어요...! 👏

2023-02-01 22:49 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/clerk/entity/seminar/SeminarAttendance.java
> +  private SeminarAttendanceExcuse seminarAttendanceExcuse;
말씀 주셨던 `em.flush()`, `em.clear()`를 언제 해야 할 지에 대한 참고가 될 것 같아서 여기 남깁니다.

`SeminarAttendanceExcuse`는 현님이 말씀하신 대로 사실상 `SeminarAttendance`가 그 생명주기를 모두 관리하고 있다고 봐도 무방합니다. (실제로 한 테이블에 합쳐도 상관 없으니까요)

그렇다면 `SeminarAttendanceExcuseRepository`에 직접 접근해서 사유를 적는 대신 아래와 같이 해보면 어떨까요?
1. `cascade = ALL` 적용
2. 연관관계 편의 메서드 작성

```java
public class SeminarAttendance {
  @OneToOne(mappedBy = "seminarAttendance", fetch = FetchType.LAZY, cascade = CascadeType.REMOVE)
  private SeminarAttendanceExcuse seminarAttendanceExcuse;

  public void 지각(String excuse) {
    seminarAttendanceStatus = getSeminarAttendanceStatusBy(LATENESS);
    seminarAttendanceExcuse = SeminarAttendanceExcuse.builder()
        .seminarAttendance(this)
        .excuse(excuse)
        .build();
  }
}
```

혹시나 결석 했을 때에도 사유를 적어야 된다면 비슷한 느낌으로 지각, 결석에 대해 적을 수 있을 것 같습니다!

이렇게 도메인에서 로직을 관리하게 되면, 나중에 서비스에서 가져다 쓸 때 코드도 깔끔해지고 굉장히 편해지더라구요!

이렇게 작성하시고 나면 테스트에서도 `em.flush()`나 `em.clear()` 없이 동작할거에요.
`em.flush()`나 `em.clear()`는 테스트 가독성도 떨어뜨리고 불필요한 쿼리를 날리기 때문에 꼭 필요할 때가 아니면 지양하는게 좋습니다.

+) 여담으로, `em.flush()`나 `em.clear()`를 지웠을 때 테스트가 터진 건 아마도 `attendance.getSeminarAttendanceExcuse()`를 했을 때 `attendance` 입장에선 `seminarAttendanceExcuse`가 `null`이라 터진걸거에요. `em.flush()`, `em.clear()` 후에 다시 찾아오는 과정에서 그 값이 들어갔을거구여!

+) 또 여담으로 `attendance.getSeminarAttendanceExcuse()`가 너무 길지 않나요..? ㅋㅋㅋㅋ 
`@Getter`를 각 컬럼에 명시해주고, `SeminarAttendanceExcuse`에선 getter를 빼버리구 아래와 같은 메서드를 만들어도 좋을 것 같습니다!

```java
public Optinal<String> getExcuse() {
    if (this.getSeminarAttendanceExcuse() == null) {
        return Optional.empty();
    }
    return Optional.ofNullable(this.getSeminarAttendanceExcuse().getAbsenceExcuse());
}
```

2023-02-02 11:00 UTC, hyuunnn commented on src/main/java/com/keeper/homepage/domain/clerk/entity/seminar/Seminar.java
> +  private static final int ATTENDANCE_CODE_LENGTH = 10;
수정했습니다!

2023-02-02 11:00 UTC, hyuunnn commented on src/main/java/com/keeper/homepage/domain/clerk/entity/seminar/SeminarAttendanceStatus.java
> +          .orElseThrow(() -> new IllegalArgumentException(format("%s 타입이 DB에 존재하지 않습니다.", dbData)));
수정했습니다 감사합니다 :)

2023-02-02 11:01 UTC, hyuunnn commented on src/test/java/com/keeper/homepage/domain/clerk/seminar/dao/SeminarAttendanceStatusRepositoryTest.java
> +      assertThat(getName(dbAllStatusTypes)).containsAll(getName(allStatusTypesEnum));
타입 비교를 까먹고 있었네요 감사합니다!

2023-02-02 11:06 UTC, hyuunnn commented on src/main/java/com/keeper/homepage/domain/clerk/entity/seminar/Seminar.java
> +  private LocalDateTime registerTime;
@gusah009 영한님 강의에서도 언급되었던 것 같은데 DB 명세를 보지 않고 코드만 봐도 구조를 파악할 수 있어야 한다는 점에서 어떻게 생각하시나요?
나중에 DB를 뜯었더니 새로운 컬럼이 있네? 할 수도 있지 않을까 생각이 들어서요 ㅎㅎ

2023-02-02 11:32 UTC, hyuunnn commented on src/test/java/com/keeper/homepage/domain/clerk/seminar/SeminarTestHelper.java
> +          .openTime(sampleTime)
@woo-chang 테스트 코드를 작성하면서 의문이 생겼는데, DB에서 넣어주는 CURRNET_TIME과 LocalDateTime.now()를 비교하는 과정에서 오차가 있을 것 같은데 혹시 좋은 방법이 있을까요?

테스트 코드는 상황에 따라서 실패가 될 수 있는게 아닌, 항상 성공해야 할텐데요..

2023-02-02 11:40 UTC, woo-chang commented on src/test/java/com/keeper/homepage/domain/clerk/seminar/SeminarTestHelper.java
> +          .openTime(sampleTime)
@hyuunnn `DB` 디폴트 값을 이용한다면 정확한 시간을 비교하기보다는

시간을 지정하지 않았지만, DB 저장 후 다시 조회했을 때 **저장 시간이 존재하는지 여부**를 테스트하는건 어떠신가요?

2023-02-02 17:04 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/clerk/entity/seminar/Seminar.java
> +  private LocalDateTime registerTime;
저도 궁금해요... 넣는게 나을까요 빼는게 나을까요? 정답은 없는 걸까요...

2023-02-03 16:11 UTC, hyuunnn commented
불필요한 Cascade 설정 때문에 꼬여있었는데, 연관관계 편의 메서드를 사용하는 방법으로 해결하였습니다..! `@OneToOne`을 사용하기 때문에 `null`이 아닌 경우 `changeAbsenceExcuse` 메서드로 값을 수정하는 방법을 선택하였습니다. (@woo-chang 좋은 아이디어 감사합니다! - 상황에 따라 Cascade 또는 연관관계 편의 메서드를 사용하는 방법 중에서 저울질이 필요하다는 것을 알게 되었습니다 ㅎ..)

그럼에도 `seminarAttendaneStatus` 변수에 `CascadeType.REMOVE`를 설정한 이유는 `SeminarAttendance`의 데이터가 삭제되었을 때 status 값도 삭제되어야 하기 때문입니다. (하나의 attendance에 여러 개의 status가 저장되기 때문입니다.)

그리고 `SeminarAttendanceTestHelper` 클래스를 삭제하였는데, 그 이유는 builder를 만들 때 많은 파라미터를 요구하지 않기 때문입니다.
```java
// SeminarAttendanceRepositoryTest.java
seminar = seminarTestHelper.generate();
member = memberTestHelper.generate();
statusType = ATTENDANCE;
seminarAttendance = seminarAttendanceRepository.save(SeminarAttendance.builder()
    .seminar(seminar)
    .member(member)
    .seminarAttendanceStatus(initAttendanceStatus(statusType))
    .build());
```
`seminar`, `member`는`generate()` 메서드를 사용하면 한 줄로 해결할 수 있습니다.

마지막으로 테스트 코드에서 불필요한 기능들을 수정하고, 테스트 케이스를 추가하였습니다.

2023-02-03 23:54 UTC, shkisme approved these changes
정말 수고하셨습니다!! 👍👍 커멘트에 자세한 코드 설명 감사합니다.
BaseEntity 만들어주세요 ㅎㅎㅎ

2023-02-03 23:54 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/clerk/entity/seminar/SeminarAttendanceExcuse.java
> +  public void changeAbsenceExcuse(String excuse) {
이건 `absenceExcuse`에 `@Setter` 사용하면 `setAbsenceExcuse(excuse)` 로 사용이 가능할 것 같은데 따로 추가하신 이유가 있나요? 특별한 의미를 담고 싶으셨던 건지 궁금합니다!

2023-02-03 23:54 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/clerk/seminar/dao/SeminarAttendanceStatusRepositoryTest.java
> +    }
👍👍👍

2023-02-04 00:07 UTC, hyuunnn commented on src/main/java/com/keeper/homepage/domain/clerk/entity/seminar/SeminarAttendanceExcuse.java
> +  public void changeAbsenceExcuse(String excuse) {
말씀하신 이유 맞습니다 ㅎㅎ
https://jeongkyun-it.tistory.com/221
https://yoonbing9.tistory.com/28
https://heewon26.tistory.com/88
https://velog.io/@gentledot/ddd-domain-model

2023-02-04 06:18 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/clerk/entity/seminar/Seminar.java
> +  private LocalDateTime registerTime;
완전히 선택의 영역이어서 어떤걸 선택해도 큰 지장은 없을 것 같습니다!

@shkisme PM님 선택에 따라 하나로 통일하기만 하면 될 것 같아요!

2023-02-04 06:19 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/clerk/seminar/SeminarTestHelper.java
> +          .openTime(sampleTime)
저는 `LocalDateTime.after()` 메서드를 활용하긴 합니다!

2023-02-04 06:32 UTC, gusah009 requested changes
GOOOOOOOOOD

2023-02-04 06:32 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/clerk/entity/seminar/SeminarAttendance.java
> +  private SeminarAttendanceStatus seminarAttendanceStatus;
`SeminarATtendanceStatus`에 `cascade REMOVE`가 걸려 있는데, 이렇게 되면 출석을 삭제할 때 `Status`도 함께 삭제됩니다.

2023-02-04 06:32 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/clerk/entity/seminar/SeminarAttendance.java
> +  }
👍👍

2023-02-04 06:54 UTC, hyuunnn commented on src/main/java/com/keeper/homepage/domain/clerk/entity/seminar/SeminarAttendance.java
> +  private SeminarAttendanceStatus seminarAttendanceStatus;
아 `Status`는 바뀌지 않는 데이터라서 삭제하면 안되겠네요.. 감사합니다!

2023-02-04 07:14 UTC, gusah009 approved these changes
수고많으셨씁니다!!

중요한건 꺾이지 않는 마음...

2023-02-04 07:14 UTC, gusah009 commented on src/main/java/com/keeper/homepage/global/error/ErrorCode.java
> +  SEMINAR_TYPE_NOT_FOUND("존재하지 않는 세미나 타입입니다.", HttpStatus.NOT_FOUND);
소소한 팁)

`java`에선 아래와 같이 마지막에 쉼표를 붙이고도 `ENUM` 선언이 됩니다.

자주 원소가 추가 될 `ENUM`이면 아래와 같이 해놓으면 가독성이 더 좋습니다.

```java
enum Number {
    ONE,
    TWO,
    THREE,
    ;
}
```

2023-02-04 07:28 UTC, hyuunnn commented on src/test/java/com/keeper/homepage/domain/clerk/seminar/SeminarTestHelper.java
> +          .openTime(sampleTime)
@gusah009 단순히 null 체크하는 것보다 `isAfter`를 사용하는게 더 좋겠네요!

2023-02-04 07:32 UTC, woo-chang approved these changes
수고하셨습니다 👍👍

2023-02-04 09:25 UTC, gusah009 approved these changes

2023-02-04 12:54 UTC, merged