feat: Study Entity, Repository 생성
KEEPER31337/Homepage-Back-R2 pull request #95
Opened 2023-02-08 14:22 UTC by xet-a

## 🔥 Related Issue

close: #9 

## 📝 Description

Study Entity와 Repository 생성했습니다!

## ⭐️ Review

**1. 기존과 다른 방식으로 복합키를 사용해보았습니다!**

`StudyHasMember` Entity에서 `study id`와 `member id`를 복합키로 가지는데요. 기존에는 DB 중심 방식인 `@IdClass` 어노테이션을 사용했는데, 객체 지향적인 방식인 `@Embeddable` 어노테이션을 사용해봤습니다. 본질적으로 차이는 없는데, 객체 지향적인 방법이 더 좋은 것 같고, 엔티티 작성 시 드는 비용을 줄일 수 있다고 우창 선배님 블로그에서 봐서.. 바꿔보았어요.

`@OneToMany(mappedBy = "study", orphanRemoval = true)`
⬇
`@OneToMany(mappedBy = "studyHasMemberPK.study", orphanRemoval = true)`

확실히 `@Embeddable`을 사용하면 연관 관계에서 컬럼 참조할 때 이렇게 복잡해지긴 하더라고요. 키를 자주 참조해야 할 때는 `@IdClass`가 훨씬 간편할 것 같아요.

일관되게 사용하는 게 좋다고 하는데, 뭐가 더 나을까요..?? 의견이 궁금합니다!

cc) https://woo-chang.tistory.com/43 (( 감사합니당 ))
https://joont92.github.io/page/12/

---

**2. 기존에 없던 빌더 패턴을 저도 따라 작성했는데, 맞게 수정한 건지 잘 모르겠어요...**

``` java
@OneToMany(mappedBy = "study", orphanRemoval = true)
@Builder.Default
private List<StudyHasMemberEntity> studyHasMemberEntities = new ArrayList<>();
```

원래 지정된 값을 넘길 수 있는 `@Buillder.Default` 어노테이션이 있는데, 이 어노테이션은 클래스 상단에 `@Builder` 어노테이션이 있어야 하고, 내부에 빌더 패턴을 사용하면 안 되는 것 같더라고요. (약간의.. 뇌피셜)

``` java
@OneToMany(mappedBy = "studyHasMemberPK.study", orphanRemoval = true)
private List<StudyHasMember> studyHasMember = new ArrayList<>();
```

그래서 없앴습니다... 그리고 빌더 패턴에 아래 코드를 추가했는데.. 맞겠죠?.. 맞을까요? 모르겠어요..

`this.studyHasMember = studyHasMember;`

---

하핫 기존에 없는 스터디 테스트도 다시 작성해서 추가할게요. 까먹을까봐 미리 pr부터 작성했어요!!
코드 리뷰만 하다 끝날 것 같았는데.. 시작이라도 해서 다행이고.. 재밌는데 어렵네요.. 사실 테스트가 제일 무서워요 흑흑

2023-02-09 01:38 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/study/entity/Study.java
> +  private LocalDateTime updateTime;
그렇습니다! `BaseEntity`를 상속받으시면 될 것 같습니다!

2023-02-09 01:50 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMember.java
> +public class StudyHasMember implements Serializable {
`@NoArgsConstructor(access = AccessLevel.PROTECTED)` 처럼 access level을 조정하면, 외부에서 마음대로 생성하는 것을 방지할 수 있고, 이는 유지보수에 좋은 것 같습니다!

2023-02-09 02:18 UTC, shkisme reviewed
수고하셨습니다 !! 리뷰 확인 부탁드려요!

2023-02-09 02:18 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/study/entity/Study.java
> +  private List<StudyHasMember> studyHasMember = new ArrayList<>();
다음을 테스트 코드로 작성해보시면 좋을 것 같습니다!

- 정말 `studyHasMember`에 `StudyHasMember`가 잘 들어가는지
- `StudyHasMember`의 생명 주기를 `Study`가 관리하게 만들었다면 관리가 잘 되는지
- `orphanRemoval` 속성을 붙여주었기 때문에 `Study`가 지워지면 `StudyHasMember`도 잘 지워지는지

2023-02-12 05:53 UTC, xet-a commented on src/main/java/com/keeper/homepage/domain/study/entity/Study.java
> +  private LocalDateTime updateTime;
넵 알겠습니다! 지난 주 PR에서 이미 다뤘던 내용인데 놓쳤더라고요 감사합니다 🙇‍♀️

2023-02-12 06:09 UTC, xet-a commented on src/main/java/com/keeper/homepage/domain/study/entity/Study.java
> +      this.studyHasMember = studyHasMember;
넵 알겠습니다!!

2023-02-12 06:12 UTC, xet-a commented on src/main/java/com/keeper/homepage/domain/study/entity/Study.java
> +  private List<StudyHasMember> studyHasMember = new ArrayList<>();
해당 섹션 강의를 안 듣고 구현하다 놓쳤습니다.. 😓 `cascade` 수정하겠습니다. `orphanRemoval` 은 기존 코드에 있던 그대로 썼는데, 말씀하신대로 스터디와 연관관계가 끊어지면 스터디원 리스트가 자동으로 삭제되는 구조인 것 같습니다!

2023-02-12 06:15 UTC, xet-a commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMember.java
> +public class StudyHasMember implements Serializable {
중복된 `Builder` 어노테이션 지웠습니다!
현경님 말씀대로 `@NoArgsConstructor(access = AccessLevel.PROTECTED)`로 수정할게요. 알려주셔서 감사합니다!

2023-02-12 06:33 UTC, xet-a commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMemberPK.java
> +  private Member member;
네 알겠습니다!

2023-02-12 06:48 UTC, xet-a commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMemberPK.java
> +public class StudyHasMemberPK implements Serializable {
복합키를 매핑할 때 두 객체가 같은 객체인지, 내부의 값이 동일한지 확인하는 `EqualsAndHashCode` 어노테이션을 사용해야 합니다. 연관관계가 복잡해지거나 필드 값이 변경되면 테스트 시 오류가 발생해서 파라미터에 "id" 값을 명시해주는 것이 좋다고 합니다!
둘 다 id 값이기도 하고, [스터디-스터디원]을 매핑한(?) `StudyHasMember`를 리스트에 담아 관리하므로 `member id` 필드가 변경되는 구조는 아닌 것 같아... 따로 명시하지는 않았습니다. 맞겠죠..?
사실 쓰면서도 이해가 잘 안 돼서.. 테스트 작성하면서 더 이해해보겠습니다!

기존에 있던 `Data` 어노테이션은 `@Getter`, `@Setter`, `@ToString`, `@EqualsAndHashCode`, `@RequiredArgsConstructor`를 자동으로 적용해주는데, 지양하는 것이 좋다고 하여서 필요한 어노테이션만 따로 명시했습니다.

2023-02-12 06:49 UTC, xet-a commented on src/main/java/com/keeper/homepage/domain/study/entity/Study.java
> +  private List<StudyHasMember> studyHasMember = new ArrayList<>();
네 감사합니다!! 감이 잘 안 왔는데... 테스트 코드 작성하면서 다시 구조 이해해보겠습니다!

2023-02-12 22:37 UTC, hyuunnn requested changes
다른 분들이 열심히 피드백 해주셨네요.. ㅎㅎ

2023-02-12 22:37 UTC, hyuunnn commented on src/main/java/com/keeper/homepage/domain/study/entity/Study.java
> +  private String information;
숫자를 상수로 표현하면 더 좋을 것 같아요. <a href="https://github.com/KEEPER31337/Homepage-Back-R2/blob/develop/src/main/java/com/keeper/homepage/domain/member/entity/job/MemberJob.java#L30">예시 링크</a>

2023-02-13 01:39 UTC, xet-a commented on src/main/java/com/keeper/homepage/domain/study/entity/Study.java
> +  private String information;
네! 감사합니다!!

2023-02-13 05:40 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMemberPK.java
> +public class StudyHasMemberPK implements Serializable {
커멘트를 이제 확인했네요! 늦어서 죄송합니다 ㅎㅎ...

> 복합키를 매핑할 때 두 객체가 같은 객체인지, 내부의 값이 동일한지 확인하는 EqualsAndHashCode 어노테이션을 사용해야 합니다. 연관관계가 복잡해지거나 필드 값이 변경되면 테스트 시 오류가 발생해서 파라미터에 "id" 값을 명시해주는 것이 좋다고 합니다!

어떤 파라미터에 `id`를 명시한다는 말씀이신가요? 해당 클래스엔 `id` 필드가 없어보여서 질문드립니다!

> 둘 다 id 값이기도 하고, [스터디-스터디원]을 매핑한(?) StudyHasMember를 리스트에 담아 관리하므로 member id 필드가 변경되는 구조는 아닌 것 같아... 따로 명시하지는 않았습니다. 맞겠죠..?

어떤 걸 따로 명시하지 않았다는 뜻일까요..?

> 기존에 있던 Data 어노테이션은 @Getter, @Setter, @ToString, @EqualsAndHashCode, @RequiredArgsConstructor를 자동으로 적용해주는데, 지양하는 것이 좋다고 하여서 필요한 어노테이션만 따로 명시했습니다.

`@Data` 대신 필요한 어노테이션만 명시한 건 좋은 것 같습니다 ㅎㅎ

그런데 이게 어떤 질문에 대한 답변인지 알 수 있을까요...? 갑자기 맥락과 관련 없이 튀어나온 것 같아서 질문드립니다!

2023-02-13 05:42 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMember.java
> +public class StudyHasMember implements Serializable {
@xet-a 왜 `AccessLevel을 PRIVATE`으로 하지 않고 `PROTECTED`로 하는 지 알 수 있을까요?

2023-02-13 05:42 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMember.java
> +  }
@shkisme DB의 시간을 기준으로 `registerTime`을 쓸 건지, 서버 시간을 기준으로 쓸 건지 확실하게 정하고 가야될 것 같아요!

2023-02-13 05:46 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMember.java
> +  }
DB 에서 현재 시간으로 설정되도록 이미 `TRIGGER`가 걸려 있어서, DB 시간 기준으로 하면 좋을 것 같은데, 팀원들에게도 전달하도록 하겠습니다!

2023-02-13 10:12 UTC, xet-a commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMember.java
> +public class StudyHasMember implements Serializable {
앗 `Private` 입니다 😓😓

2023-02-13 11:02 UTC, woo-chang reviewed
다른 분들이 리뷰를 잘해주셔서 질문만 남겨뒀습니다 ~

많이 고민하신게 보이네요! 수고하셨습니다 👍👍

2023-02-13 11:02 UTC, woo-chang commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMember.java
> +public class StudyHasMember implements Serializable {
@gusah009 정말 좋은 질문입니다 👍 저도 다시 한번 생각해볼 수 있었네요

2023-02-15 11:49 UTC, shkisme reviewed
정말 수고 많으셨어요 !! 👍👍👍

2023-02-15 11:49 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMember.java
> +@EqualsAndHashCode
그냥 `@EqualsAndHashCode` 어노테이션을 붙여주면 모든 필드를 기준으로 해서 동작한다고 말씀하셨던 것 같은데 그러면 추가된 `registerTime`이 포함될 것 같습니다! 아닌가용?

2023-02-15 11:49 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMember.java
> +  private LocalDateTime registerTime;
`StudyHasMember`에 `registerTime` 필드만 있는게 다른 테이블들과 통일감이 없긴 하네요 😇

2023-02-15 11:49 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMember.java
> +  private Member member;
속성에 `updateable = false`를 주신 이유가 있나요?

2023-02-15 11:49 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/study/StudyTestHelper.java
> +          .memberNumber(memberNumber != null ? memberNumber : 0)
`memberNumber`는 `null` 로 넣어도 DB 에서 자동으로 0을 부여해주는 것 같아서 null 체크를 빼도 괜찮겠네요!

2023-02-15 11:49 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/study/StudyTestHelper.java
> +public class StudyTestHelper {
`StudyTestHelper`를 잘 만드신 것 같아요 😎

2023-02-15 11:49 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/study/dao/StudyRepositoryTest.java
> +          .build();
지금도 괜찮지만 어렵게 만드신 `StudyTestHelper`를 활용해보셔도 좋을 것 같아요 ㅎㅎ

2023-02-15 11:49 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/study/dao/StudyRepositoryTest.java
> +      assertThat(savedStudy.getThumbnail().getId()).isEqualTo(1L);
이렇게 테스트를 작성해두면 DB를 보지 않아도 db default 값이 무엇인지 알 수 있어서 테스트는 문서의 기능도 해주는 것 같아요 👍

2023-02-15 14:57 UTC, xet-a commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMember.java
> +public class StudyHasMember implements Serializable {
@gusah009 `AccessLevel`을 `PRIVATE`으로 할 경우 다음과 같은 오류가 발생하는데,

> Class '~Entity' should have [public, protected] no-arg constructor 

이는 매개변수가 없는 생성자의 접근 레벨은 `public` 또는 `protected`로 해야 함을 의미합니다.

✔ 왜 그런지 찾아보니 프록시 조회와 관련이 있다고 합니다! 실제 `Entity`를 바로 조회하는 경우가 아니라 `Proxy` 객체로 조회되는 경우가 있는데, 이때 접근 권한이 `PRIVATE`이라면 오류가 발생하게 됩니다.
cc) https://erjuer.tistory.com/106

2023-02-15 15:13 UTC, xet-a commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMember.java
> +@EqualsAndHashCode
맞습니다! `registerTime`이 자주 변경될 값은 아닌 것 같아 따로 명시하지 않았는데, 혹시 모르니까... id 기준으로 옵션을 걸어주는 게 맞는 것 같습니다... ㅎㅎ 수정할게요! 😀

---

`@EqualsAndHashCode`에서 왜 of를 사용하는지 정리해보았습니다. ㅎㅎ
- 양방향 연관 관계 같이 연관 관계가 복잡해지면, 서로 다른 연관 관계를 순환 참조하면서 무한루프가 발생할 수 있습니다.
- 필드 하나만 바뀌어도 `hashCode()` 메서드에서 다른 해시코드가 나오기 때문에, 자주 변경되는 필드는 제외해주거나(`Exclude`) id 같이 식별자가 되는 특정 필드명을 지정(`of`)해주어야 합니다.

=> 이건 롬복 버그 시나리오를 보다가 알게 된 내용인데, 코드도 같이 보시면 좋을 것 같아 링크 남기겠습니다!
cc) https://jake-seo-dev.tistory.com/70

2023-02-15 15:15 UTC, xet-a commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMember.java
> +  private LocalDateTime registerTime;
그러게요! 😂 `registerTime` 필드 혼자 쓰는 게 여기밖에 없는 것 같아요..!

2023-02-15 15:16 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMember.java
> +@EqualsAndHashCode
생각해보니 정말 값이 변할 일은 거의 없겠네요 ㅋㅋㅋㅋ 개발자님 편하신 방향으로 가면 될듯 👍👍

2023-02-15 15:19 UTC, xet-a commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMember.java
> +  private Member member;
`StudyHasMember`가 스터디-회원이 각각 저장되는 테이블인데 `study`나 `member`가 수정되지 않을 것 같아서 속성을 줬어요.. 뭔가 꽉 막힌 것 같나요..? 잘못 사용한 것 같기도 하고... 😓

2023-02-15 15:20 UTC, xet-a commented on src/test/java/com/keeper/homepage/domain/study/StudyTestHelper.java
> +          .memberNumber(memberNumber != null ? memberNumber : 0)
네넵! 처음 작성할 때 빌더에도 다 써야 하는 줄 알고 ㅎㅎ...ㅠ 썼습니다..

2023-02-15 15:21 UTC, xet-a commented on src/test/java/com/keeper/homepage/domain/study/StudyTestHelper.java
> +public class StudyTestHelper {
감사해요!! 🙇‍♀️👍

2023-02-15 15:22 UTC, xet-a commented on src/test/java/com/keeper/homepage/domain/study/dao/StudyRepositoryTest.java
> +          .build();
사실 `TestHelper`에 default 있는 필드를 다 채워버려서.. 귀찮아서 따로 썼습니다. ㅎㅎ휴ㅠㅠ `TestHelper` 수정하면서 이 부분도 활용해서 다시 써볼게요!

2023-02-15 15:23 UTC, xet-a commented on src/test/java/com/keeper/homepage/domain/study/dao/StudyRepositoryTest.java
> +      assertThat(savedStudy.getThumbnail().getId()).isEqualTo(1L);
그러게요!! 테스트 처음 작성할 때는 마냥 어려웠는데 쓰다보니까 조금 재밌는 것 같아요 😂 조금..

2023-02-15 15:27 UTC, xet-a commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMember.java
> +@EqualsAndHashCode
아하..! 그런데 동일한 `StudyHasMember`는 테스트 할 때 생기는 경우인가요??
스터디 A에 회원 B, C가 있으면 [A, B, time], [A, C, time] 요런 식으로 객체가 생긴다고 이해하고 있었는데.. 이해가 아직 부족한가봐요...

2023-02-15 15:40 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMember.java
> +@EqualsAndHashCode
거의 없을 상황일 것 같긴 한데, 만약 회원 A가 스터디 B에 아침에 등록을 하고, 회원 A가 자기가 등록한 일을 까먹고 저녁에 스터디 B에 등록하게 된다면.... [A, B, 아침], [A, B, 저녁] 이렇게 객체가 생기게 될 것 같아요. (사실 이렇게 등록이 될 거 같진 않지만요) 그럼 두 객체를 다르게 인식하게 되겠죠...?
다음은 제가 작업한 `Member` 엔티티의 `MemberHasCommentLike`, `MemberHasCommentDislike` 입니다!

```java
@OneToMany(mappedBy = "member", cascade = ALL, orphanRemoval = true)
private final Set<MemberHasCommentLike> commentLikes = new HashSet<>();

@OneToMany(mappedBy = "member", cascade = ALL, orphanRemoval = true)
private final Set<MemberHasCommentDislike> commentDislikes = new HashSet<>();
```
`Set` 자료구조에는 중복된 값이 들어가지 않습니다. 그래서 `Member`와 `Comment`의 `id` 값으로 동일성을 검증하게 설정한 `MemberHasCommentLike`가 중복된 값이면 추가가 되지 않겠죠. 이 덕분에 혹시 모를 불필요한 row 생성을 막을 수 있을 것이라 생각합니다!

2023-02-16 02:56 UTC, xet-a commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMember.java
> +@EqualsAndHashCode
그렇군요!! `Set`으로 바꿔야 하나 고민했는데 명쾌하네요 😀
훨씬 좋은 것 같아요 감사합니다!

2023-02-16 11:10 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMember.java
> +public class StudyHasMember implements Serializable {
훌륭합니다..!

2023-02-16 11:56 UTC, xet-a commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMemberPK.java
> +public class StudyHasMemberPK implements Serializable {
커멘트를 바로 남기고 싶었는데 앞 커멘트를 뇌 빼고 썼는지.... 너무 지저분하게 썼더라고요..
반성하느라 늦었습니다 (_ _) 다시 질문해주셔서 감사합니다! 😂 앞으로는 맥락.. 챙겨서 쓸게요 ㅎㅎ

- 먼저 `@EqualsAndHashCode`에서 `of` 속성을 사용해야 하는 이유를 아래 커멘트에서 정리해두었습니다!
(그런데 저는 막상 `of` 속성을 안 써놓고 굳이.. 위에서 언급한 게..... 다시 봐도 어이가 없네요..😅)
https://github.com/KEEPER31337/Homepage-Back-R2/pull/95#discussion_r1107258336

- 위의 `StudyHasMemberPK` 클래스에는 `study`와 `member` 객체의 id가 포함됩니다!
`@EqualsAndHashCode(of={"study", "member"})` 이렇게 명시해두지 않으면 기본적으로 모든 필드를 검증하게 됩니다.
여기서는 모든 필드가 `study`, `member` 둘 밖에 없다고 생각해서 따로 명시하지 않았는데.. 큰 착각이었습니다..ㅎㅎ;


수정된 부분이 많아서 사실.. 지금 작성하는 커멘트는 큰 의미가 없지만.. 그래도 질문해주셔서 제대로 정리해볼 수 있었어요. 감사합니다! 새로 리뷰 요청할 때 수정사항 깔끔하게 정리해두겠습니다!!

2023-02-16 14:09 UTC, xet-a commented
킹현님 따라 작성해보겠읍니다. 😎

## 주요 변경 사항

( 내일 마저 수정하고 리뷰 요청할게요! )

2023-02-18 03:27 UTC, shkisme reviewed
거의 다 온 것 같습니다...!!!! 리뷰 드린거 자잘한 것들이라 조금만 수정하면 될 것 같아요 👍👍

2023-02-18 03:27 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/member/entity/Member.java
> +  }
후.. 네이밍 좋은 거 같아요 누구 아이디어인가요 😎

2023-02-18 03:27 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/study/StudyTestHelper.java
> +    private List<StudyHasMember> studyHasMember;
studyHasMember는 사용하지 않는 것 같아서 빼도 되겠네요!

2023-02-18 03:27 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/study/dao/StudyRepositoryTest.java
> +          NoSuchElementException.class);
오.. DB에서 찾을 수 없는 에러가 뜨는 지 확인하셨네요! 👍

2023-02-18 03:27 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/study/dao/StudyHasMemberRepositoryTest.java
> +      study = studyRepository.findById(study.getId()).orElseThrow();
Nit: DB에서 다시 조회하지 않아도 될 것 같아요!

2023-02-18 03:27 UTC, shkisme commented on src/test/java/com/keeper/homepage/domain/study/dao/StudyHasMemberRepositoryTest.java
> +      assertThat(studyHasMemberRepository.findById(keyB).orElseThrow());
오.. `PK`로 값이 있는 지 확인을 해보셨네요.
아마 `existsById`로 했을 땐 없으면 `boolean` `false`를 리턴하니까(에러를 throw 하지 않으니까) 그런거 아닐까요?
```java
assertThat(studyHasMemberRepository.findById(keyA)).isNotEmpty();
assertThat(studyHasMemberRepository.findById(keyB)).isNotEmpty();
```
이렇게 수정할 수 있겠네요!
`find` 시리즈들은 값이 없을 시 `Optional.empty`를 반환합니다. 이를 이용하면 좋을 것 같아요!

2023-02-18 05:14 UTC, xet-a commented on src/test/java/com/keeper/homepage/domain/study/StudyTestHelper.java
> +    private List<StudyHasMember> studyHasMember;
앗 그렇네요!!

2023-02-18 05:15 UTC, xet-a commented on src/test/java/com/keeper/homepage/domain/study/dao/StudyRepositoryTest.java
> +          NoSuchElementException.class);
`assertThrows`를 써 보고 싶었어요 ㅎㅎ

2023-02-18 05:15 UTC, xet-a commented on src/test/java/com/keeper/homepage/domain/study/dao/StudyHasMemberRepositoryTest.java
> +      study = studyRepository.findById(study.getId()).orElseThrow();
넵! 수정할게요 ㅎㅎ

2023-02-18 05:16 UTC, xet-a commented on src/test/java/com/keeper/homepage/domain/study/dao/StudyHasMemberRepositoryTest.java
> +      assertThat(studyHasMemberRepository.findById(keyB).orElseThrow());
아하.. `false`인지 체크해야 했군요! 저렇게도 해 볼게요!! 감사합니다 (_ _)

2023-02-18 11:57 UTC, gusah009 approved these changes
기나긴 여정 수고 많으셨습니닿ㅎㅎㅎㅎㅎ 👍👍

2023-02-18 11:57 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/study/entity/Study.java
> +  }
`Member`에서 스터디를 관리하는데, `Study`에서도 편의 메서드가 작성되어 있는 것 같습니다!

2023-02-18 11:57 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMember.java
> +  private Member member;
잘하신것같아요! 👍👍👍

2023-02-18 11:57 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMemberPK.java
> +@AllArgsConstructor()
Nit: `@AllArgsConstructor()` 불필요한 괄호가 있는 것 같습니다! 😄

2023-02-18 11:57 UTC, gusah009 commented on src/test/java/com/keeper/homepage/domain/study/dao/StudyHasMemberRepositoryTest.java
> +          NoSuchElementException.class);
Nit: `assertThatThrownBy`를 사용할 때 저는 개행을 아래와 같이 맞추곤 합니다!

```java
 assertThatThrownBy(() -> studyHasMemberRepository.findById(keyA).orElseThrow())
        .isInstanceOf(NoSuchElementException.class);
assertThatThrownBy(() -> studyHasMemberRepository.findById(keyB).orElseThrow())
        .isInstanceOf(NoSuchElementException.class);
```

2023-02-18 12:12 UTC, shkisme commented on src/main/java/com/keeper/homepage/domain/study/entity/Study.java
> +  }
아,, 없어도 되는군요. 방금 테스트 돌려봤습니다! ㅎㅎ,, 제 파트 쪽에도 불필요한 편의 메서드 삭제해야겠네요. 멀고 먼 cascade의 길. 😇

2023-02-18 13:54 UTC, xet-a commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMemberPK.java
> +@AllArgsConstructor()
테스트 코드에서 PK 값으로 검증하는 테스트가 있는데 이때 'AllArgsConstructor()' 어노테이션이 있어야 PK를 생성할 수 있습니다..!

2023-02-18 13:55 UTC, xet-a commented on src/test/java/com/keeper/homepage/domain/study/dao/StudyHasMemberRepositoryTest.java
> +          NoSuchElementException.class);
오오 감사합니다! 적용해볼게요 🙆🏻‍♀️

2023-02-18 14:10 UTC, gusah009 commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMemberPK.java
> +@AllArgsConstructor()
아 괄호보고 말씀드렸던 거에요! 🤣🤣

2023-02-19 13:10 UTC, xet-a commented on src/main/java/com/keeper/homepage/domain/study/entity/StudyHasMemberPK.java
> +@AllArgsConstructor()
앗 ㅋㅋ 그렇네요!! 감사합니다 😂

2023-02-19 14:06 UTC, shkisme approved these changes
수고하셨습니다 👍👍

2023-02-20 09:05 UTC, hyuunnn approved these changes
고생 많으셨습니다!!! API 개발도 화이팅!

2023-02-20 10:08 UTC, merged